name: Feature Request
description: Suggest a new feature or enhancement for SST
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please provide details to help us understand your request.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? What use case does it address?
      placeholder: |
        Example: 
        SST currently fails when semantic views reference tables that don't exist yet in CI/CD pipelines where SST runs before dbt completes.
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe your proposed solution or approach
      placeholder: |
        Example:
        Add a `--allow-missing-tables` flag that logs warnings instead of failing when tables don't exist yet, allowing partial semantic view deployments.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What alternative solutions or workarounds have you considered?
      placeholder: |
        Example:
        - Configure CI/CD to ensure dbt runs before SST (workflow orchestration)
        - Use defer mechanism to reference production tables during development
        - Manual validation before deployment

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Critical - Blocking my work
        - High - Would significantly improve workflow
        - Medium - Nice to have
        - Low - Minor improvement
    validations:
      required: true

  - type: textarea
    id: impact
    attributes:
      label: Impact
      description: Who would benefit from this feature? How widely applicable is it?
      placeholder: |
        Example:
        - Any user running SST in CI/CD pipelines (GitHub Actions, CircleCI, etc.)
        - Teams deploying semantic views and dbt models together
        - Users with complex deployment orchestration requirements

  - type: textarea
    id: technical
    attributes:
      label: Technical Considerations
      description: Any technical details, implementation ideas, or code references (optional)
      placeholder: |
        Example:
        Could modify `semantic_view_builder.py` line 497-532 (_find_table_schema method) to:
        1. Check for `--allow-missing-tables` flag
        2. Log warning instead of raising error
        3. Skip semantic view creation for missing tables
        4. Continue with remaining semantic views

  - type: textarea
    id: example
    attributes:
      label: Example Usage
      description: Show how you'd use this feature (commands, configuration, code examples)
      placeholder: |
        ```bash
        sst deploy --db ANALYTICS --schema SEMANTIC_VIEWS --allow-missing-tables
        ```
        
        Output:
        ```
        [WARNING] Table 'NEW_TABLE' not found - skipping semantic view 'NEW_VIEW'
        [SUCCESS] Created 5/6 semantic views (1 skipped)
        ```

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context, screenshots, or references

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      options:
        - label: I have searched existing issues to avoid duplicates
          required: true
        - label: I have described a clear problem and solution
          required: true
        - label: I have considered alternatives and workarounds
          required: true
