"""Apply codes: a refusal or failure while SST executes changes and runs checks in Snowflake."""

from __future__ import annotations

from ..core import ErrorSpec, Severity, spec

TITLE: str = "Apply"

SPECS: tuple[ErrorSpec, ...] = (
    spec(
        "SST-APL001",
        Severity.ERROR,
        "DDL execution failed",
        "{artifact}: {value} failed: {detail}",
        "fix the statement or the account",
    ),
    spec(
        "SST-APL002",
        Severity.WARNING,
        "Dependency failed",
        "{artifact} skipped: {blocker} failed",
        "fix the dependency and re-apply",
    ),
    spec(
        "SST-APL003",
        Severity.ERROR,
        "Blocked artifact refused",
        "{artifact} is BLOCKED by {count} errors",
        "fix the errors and re-apply",
    ),
    spec(
        "SST-APL004",
        Severity.ERROR,
        "Unsafe replacement refused",
        "{artifact}: replace statement omits COPY GRANTS",
        "emit COPY GRANTS; this is not configurable",
        demotable=False,
    ),
    spec(
        "SST-APL005",
        Severity.ERROR,
        "Plan target differs from apply target",
        "{artifact}: plan target '{found}' differs from apply target '{expected}'",
        "re-run plan against the apply target",
    ),
    spec(
        "SST-APL006",
        Severity.ERROR,
        "Smoke verification failed",
        "{count} published probes failed",
        "fix the artifacts and rerun the smoke suite",
        demotable=False,
    ),
    spec(
        "SST-APL008",
        Severity.WARNING,
        "Grants could not be verified",
        "{artifact}: grants could not be verified after replace",
        "check the grants by hand",
    ),
    spec(
        "SST-APL009",
        Severity.ERROR,
        "Explicit grant was lost",
        "{artifact}: grant {value} was present before replace and is absent after",
        "confirm COPY GRANTS was emitted",
        demotable=False,
    ),
    spec(
        "SST-APL010",
        Severity.WARNING,
        "Stale apply lock broken",
        "broke a stale lock held by {value}",
        "confirm no other run is live",
    ),
    spec(
        "SST-APL011",
        Severity.ERROR,
        "Apply lock is held",
        "{value} holds the apply lock",
        "wait for the other run or explicitly break a stale lock",
    ),
    spec(
        "SST-APL012",
        Severity.ERROR,
        "Object changed after plan",
        "{artifact}: {value} changed since the plan",
        "re-run plan",
    ),
    spec(
        "SST-APL016",
        Severity.ERROR,
        "Partial write left the artifact in an unusable state",
        "{artifact}: {detail}",
        "re-apply after reconciling the recorded physical resources",
        demotable=False,
    ),
    spec(
        "SST-APL022",
        Severity.ERROR,
        "Dataset publication failed",
        "dataset '{artifact}': {detail}",
        "check source-table and dataset privileges, then re-apply",
        demotable=False,
    ),
    spec(
        "SST-APL023",
        Severity.ERROR,
        "Eval run could not be started",
        "eval '{artifact}': {detail}",
        "check CREATE TASK, CREATE STAGE and the file format",
        demotable=False,
    ),
    spec(
        "SST-APL024",
        Severity.WARNING,
        "Eval run reported a partial terminal status",
        "eval '{artifact}': status '{found}'",
        "treat this as a failure and re-run",
    ),
    spec(
        "SST-APL028",
        Severity.ERROR,
        "Eval config stage has the wrong FILE FORMAT",
        "eval config stage '{value}': FILE FORMAT is {found}, expected {expected}",
        "alter the stage once to the required format; SST will not alter it",
        demotable=False,
    ),
    spec(
        "SST-APL100",
        Severity.ERROR,
        "Smoke probe failed",
        "{artifact}: smoke probe failed: {detail}",
        "fix the artifact and rerun the smoke suite",
        demotable=False,
    ),
    spec(
        "SST-APL900",
        Severity.ERROR,
        "Apply outcome count mismatch",
        "applied {found} outcomes for {expected} changes",
        "report this as a bug",
        demotable=False,
    ),
    spec(
        "SST-APL018",
        Severity.ERROR,
        "Registry pointer write failed after an upload",
        "{artifact}: uploaded {path}, pointer write failed: {detail}",
        "re-run apply; the uploaded trees are content-addressed and are reused",
    ),
    spec(
        "SST-APL007",
        Severity.ERROR,
        "Tag application failed after a successful create",
        "{artifact}: {detail}",
        "re-run apply; the version exists and only its certification tag is missing",
    ),
)
