"""Parsing codes: a file or field that does not have the shape, type, or value SST accepts."""

from __future__ import annotations

from ..core import ErrorSpec, Severity, spec

TITLE: str = "Parsing"

SPECS: tuple[ErrorSpec, ...] = (
    spec(
        "SST-PRS102",
        Severity.ERROR,
        "tables is explicitly empty",
        "{artifact}: 'tables: []' is not accepted",
        "declare the tables the member attaches to",
        demotable=False,
    ),
    spec(
        "SST-PRS002",
        Severity.ERROR,
        "Required field missing",
        "{artifact}: required field '{field}' is missing",
        "add the required field",
    ),
    spec(
        "SST-PRS003",
        Severity.ERROR,
        "Field has the wrong type",
        "{artifact}: '{field}' expects {expected}, found {found}",
        "change the value to the expected type",
    ),
    spec(
        "SST-PRS013",
        Severity.ERROR,
        "Value outside allowed set",
        "{artifact}: '{field}' is '{found}', expected one of {expected}",
        "use an allowed value",
    ),
    spec(
        "SST-PRS020",
        Severity.ERROR,
        "Field was renamed in 1.0",
        "{artifact}: '{field}' was renamed in 1.0; use '{expected}'",
        "rename the field",
    ),
    spec(
        "SST-PRS029",
        Severity.ERROR,
        "Synonyms block has the wrong type",
        "{artifact}: synonyms must be a list of strings, found {found}",
        "use a list of strings",
    ),
    spec(
        "SST-PRS030",
        Severity.WARNING,
        "Synonym contains problematic characters",
        "{artifact}: synonym '{value}' contains {detail}",
        "remove the punctuation",
    ),
    spec(
        "SST-PRS110",
        Severity.ERROR,
        "Relationship condition shape is invalid",
        "{artifact}: condition '{value}' does not parse to one left/right pair",
        "express one pair per condition",
    ),
    spec(
        "SST-PRS113",
        Severity.ERROR,
        "Expression field is not a string",
        "{artifact}: '{field}' expects a SQL string, found {found}",
        "supply the expression as a string",
    ),
    spec(
        "SST-PRS014",
        Severity.ERROR,
        "Mutually exclusive fields both present",
        "{artifact}: '{field}' and '{other}' are mutually exclusive",
        "declare exactly one",
    ),
    spec(
        "SST-PRS004",
        Severity.WARNING,
        "Unknown field in a known block",
        "{artifact}: unknown field '{field}'",
        "remove the field, or check the spelling",
    ),
    spec(
        "SST-PRS010",
        Severity.ERROR,
        "Identifier exceeds the object name limit",
        "'{name}' is {size} chars, over the {expected} limit",
        "shorten the name",
    ),
    spec(
        "SST-PRS015",
        Severity.ERROR,
        "Paired fields not declared together",
        "{artifact}: '{field}' requires '{other}'",
        "declare both, or neither",
    ),
    spec(
        "SST-PRS016",
        Severity.ERROR,
        "Numeric value is outside its allowed range",
        "{artifact}: '{field}' is {found}, expected {expected}",
        "use a value within the allowed range",
    ),
    spec(
        "SST-PRS025",
        Severity.ERROR,
        "Reserved agent alias used",
        "{artifact}: alias '{value}' is reserved",
        "choose a non-reserved alias",
    ),
    spec(
        "SST-PRS033",
        Severity.ERROR,
        "Required input is not a declared property",
        "{artifact}: input_schema.required names '{field}', absent from properties",
        "declare the property, or remove it from required",
    ),
    spec(
        "SST-PRS114",
        Severity.ERROR,
        "Score ranges are not contiguous",
        "{artifact}: score_ranges leave a gap or overlap at {value}",
        "make the ranges contiguous with min-inclusive, max-inclusive boundaries",
    ),
    spec(
        "SST-PRS115",
        Severity.ERROR,
        "Custom metric threshold has no usable bound",
        "{artifact}: threshold_default {found} is not a usable bound within max_score {expected}",
        "declare min, optionally max, with min <= max and both inside max_score",
    ),
    spec(
        "SST-PRS116",
        Severity.ERROR,
        "Unsupported template placeholder in a judge prompt",
        "{artifact}: '{placeholder}' is not one of the 12 supported names",
        "use a supported placeholder",
    ),
    spec(
        "SST-PRS118",
        Severity.ERROR,
        "Sample question entry has the wrong shape",
        "{artifact}: sample_questions[{index}] is a string, expected a mapping",
        "use {question: ...} mappings",
    ),
    spec(
        "SST-PRS032",
        Severity.ERROR,
        "Tool input uses unsupported object type",
        "{artifact}: input_schema property '{field}' has type '{found}'",
        "use a supported scalar or array type",
    ),
    spec(
        "SST-PRS006",
        Severity.ERROR,
        "Duplicate name within a type",
        "{type} '{name}' is declared more than once",
        "rename one declaration",
    ),
    spec(
        "SST-PRS018",
        Severity.ERROR,
        "Collection element has the wrong shape",
        "{artifact}: '{field}'[{index}] expects {expected}, found {found}",
        "correct the element",
    ),
    spec(
        "SST-PRS019",
        Severity.ERROR,
        "Boolean field holds a non-boolean",
        "{artifact}: '{field}' is '{found}', expected a boolean",
        "use true or false",
    ),
    spec(
        "SST-PRS027",
        Severity.ERROR,
        "Tags block has the wrong shape",
        "{artifact}: tags must be a list of name and value entries, found {found}",
        "write tags as a list of {name: ..., value: ...} entries",
    ),
    spec(
        "SST-PRS101",
        Severity.ERROR,
        "Required collection is empty",
        "{artifact}: '{field}' is present and empty",
        "declare at least one entry, or remove the key",
    ),
    spec(
        "SST-PRS106",
        Severity.ERROR,
        "Duplicate member name within an owner",
        "{artifact}: {member_type} '{name}' is declared twice",
        "rename one member",
    ),
    spec(
        "SST-PRS107",
        Severity.ERROR,
        "Member declares no name",
        "{artifact}: {member_type} entry {index} has no name",
        "name the member",
    ),
    spec(
        "SST-PRS034",
        Severity.ERROR,
        "Frontmatter missing a required key",
        "{artifact}: SKILL.md frontmatter omits '{field}'",
        "declare name and description in the frontmatter",
    ),
    spec(
        "SST-PRS119",
        Severity.ERROR,
        "Skill folder contains another skill folder",
        "{artifact}: nested skill folder at {path}",
        "move the nested skill beside its parent; one skill per folder",
    ),
    spec(
        "SST-PRS122",
        Severity.ERROR,
        "File is not UTF-8",
        "{file}: cannot be decoded as UTF-8 at byte {offset}",
        "save the file as UTF-8",
    ),
    spec(
        "SST-PRS123",
        Severity.ERROR,
        "Semantic view definition is malformed",
        "{artifact}: {detail}",
        "fix the field the message names; the semantic views guide lists each field's form",
    ),
    spec(
        "SST-PRS124",
        Severity.ERROR,
        "Window frame is not a frame clause",
        "{artifact}: window frame '{value}' is not ROWS or RANGE BETWEEN <bound> AND <bound>",
        "write each bound as UNBOUNDED PRECEDING, UNBOUNDED FOLLOWING, CURRENT ROW, or <n> or "
        "INTERVAL '<n> <unit>' followed by PRECEDING or FOLLOWING",
    ),
)
