"""Reference codes: a reference that does not resolve, takes a rejected form, or forms a cycle."""

from __future__ import annotations

from ..core import ErrorSpec, Severity, spec

TITLE: str = "References"

SPECS: tuple[ErrorSpec, ...] = (
    spec(
        "SST-REF001",
        Severity.ERROR,
        "ref() model not in the dbt catalog",
        "{{{{ ref('{model}') }}}} is not a model in the dbt manifest",
        "run dbt parse, or correct the model name",
    ),
    spec(
        "SST-REF005",
        Severity.ERROR,
        "metric() reference cycle",
        "metric reference cycle: {cycle}",
        "break the cycle",
    ),
    spec(
        "SST-REF002",
        Severity.ERROR,
        "ref() column not on the model",
        "{{{{ ref('{model}','{column}') }}}}: '{column}' is not a column on {model}",
        "correct the column name, or add it to the model",
    ),
    spec(
        "SST-REF006",
        Severity.ERROR,
        "Metric reference does not resolve",
        "metric('{name}') does not resolve",
        "correct the name or declare the metric",
    ),
    spec(
        "SST-REF034",
        Severity.ERROR,
        "Legacy table() global is rejected",
        "{file}:{line}:{col}: table('{model}') is not a reference in 1.0; use ref('{model}')",
        "run sst migrate refs",
    ),
    spec(
        "SST-REF035",
        Severity.ERROR,
        "Legacy column() global is rejected",
        "{file}:{line}:{col}: column('{model}','{column}') is not a reference in 1.0; use ref('{model}','{column}')",
        "run sst migrate refs",
    ),
    spec(
        "SST-REF011",
        Severity.ERROR,
        "Semantic-view reference does not resolve",
        "{{{{ semantic_view('{name}') }}}} does not resolve",
        "declare the view, or correct the reference",
    ),
    spec(
        "SST-REF012",
        Severity.ERROR,
        "Agent reference does not resolve",
        "{{{{ agent('{name}') }}}} does not resolve",
        "declare the agent, or correct the reference",
    ),
    spec(
        "SST-REF013",
        Severity.ERROR,
        "Extension reference does not resolve",
        "{{{{ extension('{name}') }}}} does not resolve",
        "declare the extension, or correct the reference",
    ),
    spec(
        "SST-REF014",
        Severity.ERROR,
        "File sidecar reference does not resolve",
        "{{{{ file('{path}') }}}} does not resolve to a file",
        "create the sidecar, or correct the path",
    ),
    spec(
        "SST-REF022",
        Severity.ERROR,
        "Agent delegation graph has a cycle",
        "agent delegation cycle: {cycle}",
        "break the delegation cycle",
    ),
    spec(
        "SST-REF026",
        Severity.ERROR,
        "Eval metric reference does not resolve",
        "{{{{ eval_metric('{name}') }}}} does not resolve",
        "declare the metric in the eval_metrics/ tree, or correct the name",
    ),
    spec(
        "SST-REF027",
        Severity.ERROR,
        "File sidecar escapes the project root",
        "{{{{ file('{path}') }}}} resolves outside the project root",
        "use a path inside the project",
    ),
    spec(
        "SST-REF010",
        Severity.ERROR,
        "Tool reference does not resolve",
        "{{{{ tool('{group}','{name}') }}}} does not resolve",
        "declare the group and member, or correct the reference",
    ),
    spec(
        "SST-REF018",
        Severity.ERROR,
        "Reference has no current-target location",
        "{{{{ {ref_function}('{name}') }}}} has no entry for target '{target}'",
        "add an explicit relation for the current dbt target",
    ),
    spec(
        "SST-REF019",
        Severity.ERROR,
        "Referenced object name is not fully qualified",
        "'{value}' is not a three-part fully-qualified name",
        "use DATABASE.SCHEMA.OBJECT",
    ),
    spec(
        "SST-REF020",
        Severity.ERROR,
        "Referenced object type is incompatible",
        "{{{{ {ref_function}('{name}') }}}} resolves to {found}, expected {expected}",
        "point the reference at a compatible object type",
    ),
    spec(
        "SST-REF023",
        Severity.WARNING,
        "Multiple targets resolve to one writable object",
        "{{{{ {ref_function}('{name}') }}}} resolves to {value} for both dev and prod",
        "map each writable target explicitly, or mark the group immutable",
    ),
    spec(
        "SST-REF032",
        Severity.ERROR,
        "skill() target not declared",
        "{{{{ skill('{name}') }}}} does not resolve",
        "declare the skill under the skills directory, or correct the name",
    ),
    spec(
        "SST-REF036",
        Severity.ERROR,
        "plugin() target not declared",
        "{{{{ plugin('{name}') }}}} does not resolve",
        "declare the plugin under the plugins directory, or correct the name",
    ),
    spec(
        "SST-REF037",
        Severity.ERROR,
        "extension() names an extension this project publishes",
        "agent '{artifact}': extension('{name}') names a {kind} this project publishes",
        "reference it with skill() or plugin(), which pins the published version",
    ),
    spec(
        "SST-REF038",
        Severity.ERROR,
        "Unknown project variable",
        "{artifact}: var('{name}') names no project variable",
        "declare it under vars: in sst_config.yml, or fix the name",
    ),
    spec(
        "SST-REF039",
        Severity.ERROR,
        "Unknown custom instruction",
        "{artifact}: custom_instructions('{name}') names no custom instruction",
        "declare it under semantic_models/custom_instructions/, or fix the name",
    ),
    spec(
        "SST-REF040",
        Severity.ERROR,
        "Unknown or invalid tag reference",
        "{artifact}: {detail}",
        "write the tag name as {{ tag('<name>') }} and declare the tag under tags: in sst_config.yml",
    ),
    spec(
        "SST-REF041",
        Severity.ERROR,
        "Template function not allowed in this field",
        "{artifact}: {function}() is not allowed in {field}",
        "remove the call; each field accepts only the functions its reference page lists",
    ),
    spec(
        "SST-REF042",
        Severity.ERROR,
        "Invalid template arguments",
        "{artifact}: {detail}",
        "ref() takes a model and an optional column; metric(), var(), and tag() take one name",
    ),
    spec(
        "SST-REF043",
        Severity.ERROR,
        "Expression references a table outside the view",
        "{artifact}: ref('{model}') is not one of the view's tables",
        "add the model to the view's tables:, or reference one of them",
    ),
    spec(
        "SST-REF044",
        Severity.ERROR,
        "View table entry is not a ref()",
        "{artifact}: table entry {found} is not a {{{{ ref('<model>') }}}} call",
        "write each tables: entry as {{ ref('<model>') }}",
    ),
    spec(
        "SST-REF045",
        Severity.ERROR,
        "Relationship endpoint is written as a ref() call",
        "{artifact}: {field} is written as {found}; it takes the bare model name",
        "run sst migrate refs --write, or write the model name",
    ),
)
