"""Semantic view validation codes, SST-VAL000 to SST-VAL499.

Names, descriptions, and connected validation (0xx), metrics (1xx), relationships (2xx),
column metadata and keys (3xx), and filters, verified queries, and compiled expressions (4xx).
"""

from __future__ import annotations

from snowflake_semantic_tools.domain.model.diagnostic.core import ErrorSpec, Severity, spec

TITLE: str = "Validation"

SPECS: tuple[ErrorSpec, ...] = (
    spec(
        "SST-VAL001",
        Severity.ERROR,
        "Name is not unique within its type",
        "{type} '{name}' is declared more than once",
        "rename one of them",
    ),
    spec(
        "SST-VAL003",
        Severity.WARNING,
        "Description missing",
        "{type} '{name}' has no description",
        "add a description; it is how Analyst chooses between objects",
    ),
    spec(
        "SST-VAL101",
        Severity.ERROR,
        "Metric expression is not an aggregate",
        "metric '{metric}' is table-scoped and its expr is not an aggregate",
        "wrap the expression in an aggregate; for a window, move OVER (...) into a window: block",
    ),
    spec(
        "SST-VAL102",
        Severity.ERROR,
        "Window function in a derived metric",
        "window function {function} in derived metric '{metric}'",
        "put the window: block on a table-scoped metric; a derived metric cannot carry a window",
        demotable=False,
    ),
    spec(
        "SST-VAL103",
        Severity.ERROR,
        "Derived metric aggregates another metric",
        "derived metric '{metric}' aggregates '{other}'",
        "reference the metric without an outer aggregate",
        demotable=False,
    ),
    spec(
        "SST-VAL104",
        Severity.ERROR,
        "Derived metric references a physical column",
        "derived metric '{metric}' references column '{column}'",
        "reference metrics only, or make the metric table-scoped",
        demotable=False,
    ),
    spec(
        "SST-VAL105",
        Severity.ERROR,
        "Derived metric references an un-aggregated member",
        "derived metric '{metric}' references un-aggregated {member_type} '{other}'",
        "aggregate it in a table-scoped metric first",
        demotable=False,
    ),
    spec(
        "SST-VAL106",
        Severity.ERROR,
        "Regular metric references a derived metric",
        "metric '{metric}' is table-scoped and references derived metric '{other}'",
        "make the metric derived, or inline the expression",
        demotable=False,
    ),
    spec(
        "SST-VAL107",
        Severity.ERROR,
        "Regular metric references a non-additive metric",
        "metric '{metric}' references '{other}', which declares non_additive_dimensions",
        "remove the reference, or drop the non-additive declaration",
        demotable=False,
    ),
    spec(
        "SST-VAL108",
        Severity.ERROR,
        "Derived metric declares tables",
        "derived metric '{metric}' declares tables:",
        "remove tables; a derived metric is view-scoped",
    ),
    spec(
        "SST-VAL109",
        Severity.ERROR,
        "Table-scoped metric declares no tables",
        "metric '{metric}' is table-scoped and declares no tables:",
        "declare tables explicitly",
    ),
    spec(
        "SST-VAL110",
        Severity.WARNING,
        "Metric contains a bare identifier",
        "metric '{metric}' expression contains bare identifier '{column}'",
        "wrap it in a two-argument ref so it is checked",
    ),
    spec(
        "SST-VAL112",
        Severity.ERROR,
        "Metric reaches an undeclared table",
        "metric '{metric}' in {artifact} reaches {outside}",
        "add the table to the view or narrow the expression",
    ),
    spec(
        "SST-VAL113",
        Severity.ERROR,
        "Derived metric declares using_relationships",
        "derived metric '{metric}' declares using_relationships",
        "remove using_relationships; derived metrics have no join path",
    ),
    spec(
        "SST-VAL114",
        Severity.ERROR,
        "Relationship path starts elsewhere",
        "metric '{metric}': relationship '{other}' does not start from '{name}'",
        "name a relationship whose left side is the metric table",
    ),
    spec(
        "SST-VAL115",
        Severity.ERROR,
        "Relationship path is a chain",
        "metric '{metric}' declares a chain of {count} relationships",
        "declare one relationship, not a path",
    ),
    spec(
        "SST-VAL121",
        Severity.ERROR,
        "Access modifier is invalid",
        "metric '{metric}': access_modifier is '{found}'",
        "use public_access or private_access",
    ),
    spec(
        "SST-VAL124",
        Severity.WARNING,
        "Duplicate metric expression",
        "metric '{metric}' has the same expression as '{other}'",
        "keep one and synonym the other",
    ),
    spec(
        "SST-VAL125",
        Severity.ERROR,
        "Window entry does not resolve",
        "metric '{metric}': window {field} names {value}, which is not {expected}",
        "name a dimension the metric's table can reach, or a metric of the same table",
        demotable=False,
    ),
    spec(
        "SST-VAL126",
        Severity.ERROR,
        "Window applies to a column",
        "metric '{metric}': {function} must apply to a metric or an aggregate to be a window metric",
        "pass {{ metric() }} or an aggregate such as SUM(...); a row-level window belongs in a fact or dimension",
        demotable=False,
    ),
    spec(
        "SST-VAL127",
        Severity.ERROR,
        "Window frame without an order",
        "metric '{metric}': window frame '{value}' needs an order_by",
        "add order_by, or remove the frame",
        demotable=False,
    ),
    spec(
        "SST-VAL128",
        Severity.ERROR,
        "Metric references a window metric",
        "metric '{metric}' references '{other}', a window function metric",
        "reference the metric the window applies to instead; Snowflake does not allow a window metric in another metric",
        demotable=False,
    ),
    spec(
        "SST-VAL203",
        Severity.ERROR,
        "Relationship names a table not in the view",
        "relationship '{relationship}' names '{name}', absent from {artifact}",
        "add the table to the view, or drop the relationship",
    ),
    spec(
        "SST-VAL210",
        Severity.WARNING,
        "Relationship target has no matching key",
        "relationship '{relationship}': '{name}' declares neither primary_key nor unique_keys over {value}",
        "declare the key; it is the cheapest fan-out protection",
    ),
    spec(
        "SST-VAL214",
        Severity.ERROR,
        "Unknown relationship reference",
        "metric '{metric}' names relationship '{relationship}', which is not declared",
        "declare the relationship or correct the name",
    ),
    spec(
        "SST-VAL223",
        Severity.ERROR,
        "Primary and unique keys overlap",
        "{artifact}: column '{column}' on '{model}' appears in both primary_key and unique_keys",
        "remove it from unique_keys; a primary key is already unique",
    ),
    spec(
        "SST-VAL305",
        Severity.ERROR,
        "Fact column is not numeric",
        "{artifact}: fact '{member}' has type {found}",
        "use a numeric column, or make it a dimension",
    ),
    spec(
        "SST-VAL306",
        Severity.ERROR,
        "Time dimension column is not temporal",
        "{artifact}: time_dimension '{member}' has type {found}",
        "use a date or timestamp column, or change column_type",
    ),
    spec(
        "SST-VAL308",
        Severity.ERROR,
        "Column type metadata is absent",
        "{artifact}: column '{member}' declares no column_type",
        "declare dimension, time_dimension or fact, or run sst enrich to derive it from the column's type",
    ),
    spec(
        "SST-VAL309",
        Severity.ERROR,
        "Data type metadata is absent",
        "{artifact}: column '{member}' declares no data_type",
        "declare the Snowflake type, or run sst enrich to read it from the relation",
    ),
    spec(
        "SST-VAL310",
        Severity.ERROR,
        "Key column is absent",
        "{artifact}: primary_key names '{column}', absent from '{name}'",
        "correct the primary_key or unique_keys list",
    ),
    spec(
        "SST-VAL312",
        Severity.WARNING,
        "Table declares no key",
        "{artifact}: '{name}' declares neither primary_key nor unique_keys",
        "declare one; cardinality is otherwise guessed from data",
    ),
    spec(
        "SST-VAL314",
        Severity.ERROR,
        "Enum has no sample values",
        "{artifact}: '{member}' is is_enum and declares no sample_values",
        "populate sample_values or clear is_enum",
    ),
    spec(
        "SST-VAL315",
        Severity.WARNING,
        "Non-enum sample values look exhaustive",
        "{artifact}: '{member}' declares {count} sample_values and is not is_enum",
        "set is_enum: true if the set is complete, or is_enum: false if it is a sample; "
        "sst enrich --include enums decides from the data",
    ),
    spec(
        "SST-VAL318",
        Severity.ERROR,
        "Excluded column is referenced",
        "{artifact}: '{member}' references excluded column '{column}'",
        "un-exclude the column or change the expression",
    ),
    spec(
        "SST-VAL401",
        Severity.ERROR,
        "Filter expression is not boolean",
        "filter '{member}' carries labels: [filter] and its expr is not boolean",
        "make the expression boolean",
    ),
    spec(
        "SST-VAL316",
        Severity.WARNING,
        "Auto-managed field contains a sentinel value",
        "{artifact}: '{member}'.{field} contains '{value}'",
        "delete the value; it is a missing-value placeholder, not data. "
        "sst enrich --force sample-values collects the column again",
    ),
    spec(
        "SST-VAL325",
        Severity.WARNING,
        "Described column is absent from the relation",
        "model '{model}': column '{column}' is described in YAML and absent from the relation",
        "delete the column from the model YAML, or rebuild the model; sst enrich never deletes it",
    ),
    spec(
        "SST-VAL327",
        Severity.WARNING,
        "Declared data type differs from the relation",
        "model '{model}': column '{column}' declares data_type {declared}, and the relation has {found}",
        "correct data_type, or run sst enrich --force data-types",
    ),
    spec(
        "SST-VAL328",
        Severity.WARNING,
        "PII-tagged column carries sample values",
        "model '{model}': column '{column}' carries pii_tags and {count} sample_values",
        "delete the sample_values; sst enrich never samples a column with pii_tags",
    ),
    spec(
        "SST-VAL209",
        Severity.WARNING,
        "Ambiguous join path between two tables",
        "{artifact}: {count} paths between '{a}' and '{b}'",
        "declare using_relationships on the affected metrics",
    ),
    spec(
        "SST-VAL116",
        Severity.ERROR,
        "using_relationships absent where the join path is ambiguous",
        "metric '{metric}' has {count} paths to '{name}' and declares no using_relationships",
        "declare using_relationships to pick the path",
    ),
    spec(
        "SST-VAL020",
        Severity.INFO,
        "Connected validation unavailable",
        "connected validation skipped: {detail}",
        "connect to Snowflake to run connected checks",
    ),
    spec(
        "SST-VAL418",
        Severity.ERROR,
        "Expression does not compile against Snowflake",
        "{type} '{name}': expression failed to compile: {detail}",
        "fix the expression",
    ),
    spec(
        "SST-VAL118",
        Severity.ERROR,
        "Non-additive dimension does not resolve",
        "metric '{metric}': non_additive_dimensions names {value}, which does not resolve",
        "correct the table and dimension names",
    ),
    spec(
        "SST-VAL201",
        Severity.ERROR,
        "Relationship declares no conditions",
        "relationship '{relationship}' declares no conditions",
        "declare at least one condition",
    ),
    spec(
        "SST-VAL204",
        Severity.ERROR,
        "Relationship column is on the wrong table",
        "relationship '{relationship}': '{column}' is not on '{name}'",
        "correct the column, or swap the sides",
    ),
    spec(
        "SST-VAL215",
        Severity.ERROR,
        "Relationship graph cycle changes results",
        "{artifact}: relationship cycle {cycle}",
        "break the cycle, or split role-playing tables",
    ),
    spec(
        "SST-VAL311",
        Severity.ERROR,
        "Relationship target declares no key",
        "{artifact}: '{name}' declares neither primary_key nor unique_keys, and a relationship references it",
        "declare primary_key (or unique_keys) in the model's config.meta.sst",
    ),
    spec(
        "SST-VAL412",
        Severity.ERROR,
        "Verified-query SQL source is invalid",
        "verified_query '{member}': {detail}",
        "declare exactly one of sql or sql_file",
    ),
    spec(
        "SST-VAL413",
        Severity.WARNING,
        "Verified-query SQL reads an undeclared table",
        "verified_query '{member}': its SQL reads '{name}', which is not in its tables:",
        "add the table to tables:, which decides the views the query attaches to",
    ),
    spec(
        "SST-VAL405",
        Severity.ERROR,
        "Boolean standalone filter",
        "filter '{member}' is boolean-valued and declares no labels: key",
        "add labels: [filter] so it renders as a native LABELS = (FILTER) dimension; sst migrate refs adds it",
    ),
)
