"""Validation codes 1xx (VAL): metrics -- aggregation, derivation, tables, join paths, and windows."""

from __future__ import annotations

from snowflake_semantic_tools.domain.model.diagnostic.core import ErrorSpec, Severity, spec

TITLE: str = "Validation"

SPECS: tuple[ErrorSpec, ...] = (
    spec(
        "SST-VAL101",
        Severity.ERROR,
        "Metric expression is not an aggregate",
        "metric '{metric}' is table-scoped and its expr is not an aggregate",
        "wrap the expression in an aggregate; for a window, move OVER (...) into a window: block",
    ),
    spec(
        "SST-VAL102",
        Severity.ERROR,
        "Window function in a derived metric",
        "window function {function} in derived metric '{metric}'",
        "put the window: block on a table-scoped metric; a derived metric cannot carry a window",
        demotable=False,
    ),
    spec(
        "SST-VAL103",
        Severity.ERROR,
        "Derived metric aggregates another metric",
        "derived metric '{metric}' aggregates '{other}'",
        "reference the metric without an outer aggregate",
        demotable=False,
    ),
    spec(
        "SST-VAL104",
        Severity.ERROR,
        "Derived metric references a physical column",
        "derived metric '{metric}' references column '{column}'",
        "reference metrics only, or make the metric table-scoped",
        demotable=False,
    ),
    spec(
        "SST-VAL105",
        Severity.ERROR,
        "Derived metric references an un-aggregated member",
        "derived metric '{metric}' references un-aggregated {member_type} '{other}'",
        "aggregate it in a table-scoped metric first",
        demotable=False,
    ),
    spec(
        "SST-VAL106",
        Severity.ERROR,
        "Regular metric references a derived metric",
        "metric '{metric}' is table-scoped and references derived metric '{other}'",
        "make the metric derived, or inline the expression",
        demotable=False,
    ),
    spec(
        "SST-VAL107",
        Severity.ERROR,
        "Regular metric references a non-additive metric",
        "metric '{metric}' references '{other}', which declares non_additive_dimensions",
        "remove the reference, or drop the non-additive declaration",
        demotable=False,
    ),
    spec(
        "SST-VAL108",
        Severity.ERROR,
        "Derived metric declares tables",
        "derived metric '{metric}' declares tables:",
        "remove tables; a derived metric is view-scoped",
    ),
    spec(
        "SST-VAL109",
        Severity.ERROR,
        "Table-scoped metric declares no tables",
        "metric '{metric}' is table-scoped and declares no tables:",
        "declare tables explicitly",
    ),
    spec(
        "SST-VAL110",
        Severity.WARNING,
        "Metric contains a bare identifier",
        "metric '{metric}' expression contains bare identifier '{column}'",
        "wrap it in a two-argument ref so it is checked",
    ),
    spec(
        "SST-VAL112",
        Severity.ERROR,
        "Metric reaches an undeclared table",
        "metric '{metric}' in {artifact} reaches {outside}",
        "add the table to the view or narrow the expression",
    ),
    spec(
        "SST-VAL113",
        Severity.ERROR,
        "Derived metric declares using_relationships",
        "derived metric '{metric}' declares using_relationships",
        "remove using_relationships; derived metrics have no join path",
    ),
    spec(
        "SST-VAL114",
        Severity.ERROR,
        "Relationship path starts elsewhere",
        "metric '{metric}': relationship '{other}' does not start from '{name}'",
        "name a relationship whose left side is the metric table",
    ),
    spec(
        "SST-VAL115",
        Severity.ERROR,
        "Relationship path is a chain",
        "metric '{metric}' declares a chain of {count} relationships",
        "declare one relationship, not a path",
    ),
    spec(
        "SST-VAL116",
        Severity.ERROR,
        "using_relationships absent where the join path is ambiguous",
        "metric '{metric}' has {count} paths to '{name}' and declares no using_relationships",
        "declare using_relationships to pick the path",
    ),
    spec(
        "SST-VAL118",
        Severity.ERROR,
        "Non-additive dimension does not resolve",
        "metric '{metric}': non_additive_dimensions names {value}, which does not resolve",
        "correct the table and dimension names",
    ),
    spec(
        "SST-VAL121",
        Severity.ERROR,
        "Access modifier is invalid",
        "metric '{metric}': access_modifier is '{found}'",
        "use public_access or private_access",
    ),
    spec(
        "SST-VAL124",
        Severity.WARNING,
        "Duplicate metric expression",
        "metric '{metric}' has the same expression as '{other}'",
        "keep one and synonym the other",
    ),
    spec(
        "SST-VAL125",
        Severity.ERROR,
        "Window entry does not resolve",
        "metric '{metric}': window {field} names {value}, which is not {expected}",
        "name a dimension the metric's table can reach, or a metric of the same table",
        demotable=False,
    ),
    spec(
        "SST-VAL126",
        Severity.ERROR,
        "Window applies to a column",
        "metric '{metric}': {function} must apply to a metric or an aggregate to be a window metric",
        "pass {{ metric() }} or an aggregate such as SUM(...); a row-level window belongs in a fact or dimension",
        demotable=False,
    ),
    spec(
        "SST-VAL127",
        Severity.ERROR,
        "Window frame without an order",
        "metric '{metric}': window frame '{value}' needs an order_by",
        "add order_by, or remove the frame",
        demotable=False,
    ),
    spec(
        "SST-VAL128",
        Severity.ERROR,
        "Metric references a window metric",
        "metric '{metric}' references '{other}', a window function metric",
        "reference the metric the window applies to instead; "
        "Snowflake does not allow a window metric in another metric",
        demotable=False,
    ),
)
