"""Apply codes (APL): a refusal or failure while SST executes changes and runs checks in Snowflake."""

from __future__ import annotations

from snowflake_semantic_tools.domain.diagnostics.core import ErrorSpec, Severity, spec

TITLE: str = "Apply"

SPECS: tuple[ErrorSpec, ...] = (
    spec(
        "SST-APL001",
        Severity.ERROR,
        "DDL execution failed",
        "{artifact}: {value} failed: {detail}",
        "read internal_detail, then fix the statement or the account",
    ),
    spec(
        "SST-APL002",
        Severity.WARNING,
        "Skipped: a dependency failed",
        "{artifact} skipped: {blocker} failed",
        "fix the dependency, then re-apply",
    ),
    spec(
        "SST-APL003",
        Severity.ERROR,
        "Refused: artifact is blocked",
        "{artifact} is BLOCKED by {count} errors",
        "fix the errors, then re-apply",
    ),
    spec(
        "SST-APL004",
        Severity.ERROR,
        "Refused: replace would run without COPY GRANTS",
        "{artifact}: replace statement omits COPY GRANTS",
        "emit COPY GRANTS; this is not configurable",
        demotable=False,
    ),
    spec(
        "SST-APL005",
        Severity.ERROR,
        "Refused: plan was not computed for this target",
        "{artifact}: plan target '{found}' differs from the apply target '{expected}'",
        "re-run plan against the apply target",
    ),
    spec(
        "SST-APL006",
        Severity.ERROR,
        "Verification gate failed",
        "{count} published probes failed",
        "fix the metrics, then re-run the smoke suite; this never fails an apply",
        demotable=False,
    ),
    spec(
        "SST-APL007",
        Severity.ERROR,
        "Tag application failed after a successful create",
        "{artifact}: tags could not be applied: {detail}",
        "grant the tag privilege, then re-apply",
    ),
    spec(
        "SST-APL008",
        Severity.WARNING,
        "Grants could not be re-read after a replace",
        "{artifact}: grants could not be verified after replace",
        "check the grants by hand",
    ),
    spec(
        "SST-APL009",
        Severity.ERROR,
        "Explicit grant did not survive a replace",
        "{artifact}: grant {value} was present before replace and is absent after",
        "confirm COPY GRANTS was emitted",
        demotable=False,
    ),
    spec(
        "SST-APL010",
        Severity.WARNING,
        "Stale lock broken",
        "broke a stale lock held by {value}",
        "confirm no other run is live; a broken lock means the previous run did not exit cleanly",
    ),
    spec(
        "SST-APL011",
        Severity.ERROR,
        "Lock held by a live run",
        "{value} holds the apply lock",
        "wait for the other run, or clear the lock",
    ),
    spec(
        "SST-APL012",
        Severity.ERROR,
        "Object changed between plan and apply",
        "{artifact}: {value} changed since the plan",
        "re-run plan",
    ),
    spec(
        "SST-APL013",
        Severity.ERROR,
        "Write refused: target is a production-like environment under --temporary",
        "{artifact}: --temporary against target '{target}' is not permitted",
        "drop --temporary, or point at a scratch target",
    ),
    spec(
        "SST-APL014",
        Severity.WARNING,
        "Temporary artifact shadows a permanent one",
        "{artifact} shadows a permanent object of the same name for this session",
        "remember the change is local",
    ),
    spec(
        "SST-APL015",
        Severity.WARNING,
        "alias ignored under --temporary",
        "{artifact}: alias is meaningless under --temporary and was ignored",
        "no action; the same committed file is reusable for a permanent apply",
    ),
    spec(
        "SST-APL016",
        Severity.ERROR,
        "Partial write left the artifact in an unusable state",
        "{artifact}: {detail}",
        "re-apply, or drop and re-create",
    ),
    spec(
        "SST-APL017",
        Severity.ERROR,
        "Per-channel publish reported aggregate success",
        "{artifact}: {detail}",
        "report per-channel status separately",
    ),
    spec(
        "SST-APL018",
        Severity.ERROR,
        "Registry pointer write failed after an upload",
        "{artifact}: uploaded {path}, pointer write failed: {detail}",
        "re-run apply; the publish is half complete",
    ),
    spec(
        "SST-APL019",
        Severity.ERROR,
        "Deletion of a removed bundle file failed",
        "{artifact}: '{path}' could not be removed from the published version",
        "re-publish from empty",
    ),
    spec(
        "SST-APL020",
        Severity.ERROR,
        "Version name collided under a parallel deploy",
        "{artifact}: version '{value}' was minted twice",
        "retry; derive versions from the content SHA",
    ),
    spec(
        "SST-APL021",
        Severity.ERROR,
        "Grant issued before certification completed",
        "{artifact}: grants were issued and certification did not succeed",
        "revoke, certify, then grant",
    ),
    spec(
        "SST-APL022",
        Severity.ERROR,
        "Dataset version could not be added",
        "dataset '{artifact}': ADD VERSION failed: {detail}",
        "check OWNERSHIP on the dataset",
    ),
    spec(
        "SST-APL023",
        Severity.ERROR,
        "Eval run could not be started",
        "eval '{artifact}': {detail}",
        "check CREATE TASK, CREATE STAGE and the file format",
    ),
    spec(
        "SST-APL024",
        Severity.WARNING,
        "Eval run reported a partial terminal status",
        "eval '{artifact}': status '{found}'",
        "treat this as a failure and re-run",
    ),
    spec(
        "SST-APL027",
        Severity.ERROR,
        "Metadata table absent or the wrong shape",
        "{value}: {detail}",
        "re-run sst compile, then apply",
    ),
    spec(
        "SST-APL028",
        Severity.ERROR,
        "Eval config stage has the wrong FILE FORMAT",
        "eval config stage '{value}': FILE FORMAT is {found}, expected {expected}",
        "run one ALTER STAGE to set the required FILE FORMAT; SST will not alter a stage it did not create",
    ),
    spec(
        "SST-APL100",
        Severity.ERROR,
        "Smoke query failed",
        "{artifact}: smoke probe failed: {detail}",
        "fix the metric; a created view is not a working view",
    ),
    spec(
        "SST-APL900",
        Severity.ERROR,
        "Outcome count does not match change count",
        "applied {found} outcomes for {expected} changes",
        "report this as a bug",
    ),
)
