"""Configuration codes (CFG): `sst_config.yml` keys and values, folder routes, and dbt profiles."""

from __future__ import annotations

from snowflake_semantic_tools.domain.diagnostics.core import ErrorSpec, Severity, spec

TITLE: str = "Configuration"

SPECS: tuple[ErrorSpec, ...] = (
    spec(
        "SST-CFG001",
        Severity.ERROR,
        "No config file found",
        "no sst_config.yml at {path}",
        "create sst_config.yml at the project root, or pass --project-dir",
    ),
    spec(
        "SST-CFG002",
        Severity.ERROR,
        "Config is not valid YAML",
        "{path} is not valid YAML: {detail}",
        "fix the YAML syntax at the reported position",
    ),
    spec(
        "SST-CFG003",
        Severity.WARNING,
        "Unknown config key",
        "unknown config key '{key}'",
        "remove the key, or check it against sst docs config",
    ),
    spec(
        "SST-CFG004",
        Severity.ERROR,
        "Config value has the wrong type",
        "config key '{key}' expects {expected}, found {found}",
        "correct the value type",
    ),
    spec(
        "SST-CFG005",
        Severity.ERROR,
        "Multiple config files discoverable",
        "{count} candidate config files found; used {used}, shadowed {shadowed}",
        "delete the shadowed files, or pass --project-dir",
    ),
    spec(
        "SST-CFG006",
        Severity.ERROR,
        "Required config key missing",
        "required config key '{key}' is absent",
        "add {key} to sst_config.yml",
    ),
    spec(
        "SST-CFG007",
        Severity.ERROR,
        "Unknown top-level key near a known key",
        "unknown top-level key '{key}'; did you mean '{suggestion}'?",
        "correct the spelling",
    ),
    spec(
        "SST-CFG008",
        Severity.ERROR,
        "Config value outside its allowed domain",
        "config key '{key}' value {found} is outside {expected}",
        "use one of {expected}",
    ),
    spec(
        "SST-CFG009",
        Severity.ERROR,
        "profiles.yml not found",
        "no profiles.yml at any searched location",
        "create profiles.yml, or set DBT_PROFILES_DIR",
    ),
    spec(
        "SST-CFG010",
        Severity.ERROR,
        "Profile or target not found",
        "target '{target}' is absent from profile '{profile}'",
        "add the target, or pass --target with a declared name",
    ),
    spec(
        "SST-CFG011",
        Severity.ERROR,
        "Profile type is not snowflake",
        "profile '{profile}' declares type '{found}'",
        "point SST at a Snowflake profile",
    ),
    spec(
        "SST-CFG012",
        Severity.ERROR,
        "Credential field missing from the resolved profile",
        "profile '{profile}' has no {field}",
        "set {field} in profiles.yml or its env var",
    ),
    spec(
        "SST-CFG013",
        Severity.ERROR,
        "env_var() resolved to an empty string",
        "env_var('{var}') is unset and has no default",
        "set {var}, or give env_var() a default",
    ),
    spec(
        "SST-CFG014",
        Severity.WARNING,
        "Profile field silently empty",
        "profile '{profile}' leaves {field} empty",
        "set {field} explicitly rather than relying on account defaults",
    ),
    spec(
        "SST-CFG015",
        Severity.ERROR,
        "evals block declares a database or schema",
        "evals: declares {key}, which is structurally invalid",
        "remove +database and +schema from evals:",
    ),
    spec(
        "SST-CFG016",
        Severity.ERROR,
        "Targeting value does not resolve for the current target",
        "+{key} does not resolve for target '{target}'",
        "declare the value for every target you publish to",
    ),
    spec(
        "SST-CFG017",
        Severity.ERROR,
        "tool() reference does not resolve from config",
        "{{ tool('{group}','{name}') }} does not resolve",
        "declare the group and member in the tools directory",
    ),
    spec(
        "SST-CFG018",
        Severity.WARNING,
        "Declared tool member referenced by nothing",
        "tool member '{group}.{name}' is referenced by nothing",
        "reference it from an agent, or delete it",
    ),
    spec(
        "SST-CFG019",
        Severity.ERROR,
        "Tool member declared under both define and reference",
        "'{name}' appears under both define: and reference:",
        "choose one; a member is owned or referenced, never both",
    ),
    spec(
        "SST-CFG020",
        Severity.ERROR,
        "Per-group tools override names an unknown or reference-only group",
        "tools: override names group '{group}', which {reason}",
        "target a group that exists and contains define: members",
    ),
    spec(
        "SST-CFG023",
        Severity.ERROR,
        "max_staleness below the accepted floor",
        "+max_staleness is {found}; the minimum is 120",
        "raise max_staleness to at least 120",
    ),
    spec(
        "SST-CFG025",
        Severity.WARNING,
        "Value absent from an allowlist",
        "{kind} '{found}' is absent from {key}",
        "add it to {key}, or use an allowed value",
    ),
    spec(
        "SST-CFG029",
        Severity.ERROR,
        "var() reference has no declaration",
        "{{ var('{var}') }} is not declared in config",
        "declare {var} under vars:",
    ),
    spec(
        "SST-CFG031",
        Severity.ERROR,
        "snowflake_syntax_check is not set explicitly",
        "validation.snowflake_syntax_check is unset",
        "set it true or false explicitly",
    ),
    spec(
        "SST-CFG032",
        Severity.WARNING,
        "Config file shadows another config file",
        "using {used}; shadowed {shadowed}",
        "delete the shadowed file",
    ),
    spec(
        "SST-CFG033",
        Severity.ERROR,
        "Illegal severity override",
        "severity_overrides {code}: {found} is not permitted ({reason})",
        "promote instead of demoting, or remove the override",
        demotable=False,
    ),
    spec(
        "SST-CFG034",
        Severity.WARNING,
        "Strict flag and config key disagree",
        "--strict {flag} disagrees with validation.strict {config}; the flag wins",
        "remove one of the two",
    ),
    spec(
        "SST-CFG035",
        Severity.WARNING,
        "Baseline nearing expiry",
        "baseline expires on {date}; {count} entries remain",
        "fix the baselined diagnostics, or run sst baseline renew --reason",
    ),
    spec(
        "SST-CFG036",
        Severity.ERROR,
        "Name-map entry cannot be qualified",
        "{block}: '{name}' cannot be qualified -- no fqn: and {reason}",
        "set fqn: on the entry, or set default_prefix on the block",
    ),
    spec(
        "SST-CFG037",
        Severity.WARNING,
        "validation.strict is enforced from 1.0 and no baseline exists",
        "validation.strict: true is enforced from 1.0; {count} warnings now block",
        "run sst baseline add to hold the current warning count, then fix them",
    ),
    spec(
        "SST-CFG038",
        Severity.ERROR,
        "Sample-value collection requested but the project refuses it",
        "--include {components} reads row data, and enrichment.allow_sample_value_collection is false",
        "remove --include sample-values, or change the key in sst_config.yml",
        demotable=False,
    ),
    spec(
        "SST-CFG039",
        Severity.ERROR,
        "Baseline is past its expiry",
        "baseline expired on {date}; {count} entries resume blocking",
        "fix the baselined diagnostics, or run sst baseline renew --reason",
    ),
    spec(
        "SST-CFG040",
        Severity.ERROR,
        "`sha_version` is declared in `vars:`",
        "vars.sha_version is supplied by SST and must not be declared",
        "remove it from `vars:`; SST resolves it from the commit being published",
    ),
    spec(
        "SST-CFG041",
        Severity.ERROR,
        "Folder route names a directory that does not exist",
        "config key '{key}' in block '{block}' names no directory under '{root}'",
        "create the directory, or remove the key",
    ),
    spec(
        "SST-CFG042",
        Severity.ERROR,
        "Folder route declared under `evals:` or `skills:`",
        "{block}: declares a folder route '{key}'",
        (
            "remove it -- `evals:` location is structural, and `skills:`'s unprefixed keys are its `catalog`/`stage` "
            "sub-blocks"
        ),
    ),
    spec(
        "SST-CFG043",
        Severity.ERROR,
        "Config key was removed",
        "config key '{key}' was removed: {reason}",
        "delete the key",
    ),
    spec(
        "SST-CFG044",
        Severity.ERROR,
        "Config key is not supported in this release",
        "config key '{key}' is not supported in this release",
        "delete the key",
    ),
    spec(
        "SST-CFG046",
        Severity.ERROR,
        "Configuration requires a dbt project",
        "{key} requires a dbt project, and the project has no dbt_project.yml",
        "add dbt_project.yml, or remove the configuration; a project without dbt publishes skills, plugins, "
        "and profiles only",
    ),
    spec(
        "SST-CFG047",
        Severity.ERROR,
        "Configured directory does not exist",
        "{key} is {value}, which is not a directory in the project",
        "fix the path, or remove the key to use the default; otherwise SST finds nothing there, and "
        "--prune would remove everything that directory published",
    ),
    spec(
        "SST-CFG048",
        Severity.WARNING,
        "profiles.yml field is not used by SST",
        "target '{target}': '{key}' is not a setting SST reads, so it is ignored",
        "check the spelling; SST passes only connection settings to Snowflake, so a misspelled credential "
        "field would otherwise be dropped silently",
    ),
    spec(
        "SST-CFG049",
        Severity.ERROR,
        "profiles.yml value cannot be used",
        "target '{target}': '{key}' {problem}",
        "SST renders {{ env_var('NAME') }} and {{ env_var('NAME', 'default') }} anywhere in a value, and no "
        "other template; write numbers and booleans without filters such as as_number",
    ),
    spec(
        "SST-CFG050",
        Severity.ERROR,
        "Unsupported authentication configuration",
        "target '{target}': {detail}",
        "authenticate with a key pair, a password, SSO (authenticator), or an OAuth access token (token)",
    ),
    spec(
        "SST-CFG051",
        Severity.WARNING,
        "profiles.yml disables certificate revocation checks",
        "target '{target}': insecure_mode is true, so OCSP certificate revocation checks are off for this connection",
        (
            "remove insecure_mode, or set it to false; it is a debugging switch, and with it on a revoked certificate "
            "is still accepted"
        ),
    ),
    spec(
        "SST-CFG200",
        Severity.WARNING,
        "Deprecated config key",
        "config key '{key}' is deprecated; use '{expected}'",
        "rename the key",
    ),
)
