"""dbt seam codes (DBT): the manifest, the profile, invoking dbt, and SST metadata on dbt models."""

from __future__ import annotations

from snowflake_semantic_tools.domain.diagnostics.core import ErrorSpec, Severity, spec

TITLE: str = "dbt"

SPECS: tuple[ErrorSpec, ...] = (
    spec(
        "SST-DBT001",
        Severity.ERROR,
        "dbt manifest absent or empty",
        "no dbt models available",
        "check that the dbt project has models; under --manifest, check the path",
    ),
    spec(
        "SST-DBT002",
        Severity.ERROR,
        "dbt model referenced but absent from the manifest",
        "model '{model}' is not in the dbt manifest",
        "correct the model name, or add the model to the dbt project",
    ),
    spec(
        "SST-DBT003",
        Severity.ERROR,
        "config.meta.sst names an unknown role",
        "model '{model}': meta.sst role '{found}' is not a known role",
        "correct the role name",
    ),
    spec(
        "SST-DBT004",
        Severity.WARNING,
        "Column type in dbt disagrees with the declared type",
        "model '{model}': column '{column}' is {found} in dbt and {expected} in the semantic layer",
        "reconcile the two types, or add a dbt contract",
    ),
    spec(
        "SST-DBT005",
        Severity.ERROR,
        "dbt manifest is stale relative to the models on disk",
        "manifest is older than {value}",
        "drop --manifest and let SST parse, or rebuild the manifest you passed",
    ),
    spec(
        "SST-DBT006",
        Severity.ERROR,
        "Resolved relation differs from the model name",
        "model '{model}' resolves to relation '{value}'",
        "point the semantic layer at the resolved relation: name the model with {{ ref() }}",
    ),
    spec(
        "SST-DBT009",
        Severity.ERROR,
        "Consumed model is disabled or ephemeral",
        "model '{model}' is {found} and produces no relation",
        "enable it, or change the materialisation to a table or a view",
    ),
    spec(
        "SST-DBT010",
        Severity.ERROR,
        "Collapse safety rule violated",
        "models {a} and {b} collapse to '{value}' and differ in {column}",
        "rename one relation, or align the columns",
    ),
    spec(
        "SST-DBT011",
        Severity.ERROR,
        "Source referenced by the semantic layer is not declared in dbt",
        "source '{value}' is not declared in dbt",
        "declare the source in the dbt project",
    ),
    spec(
        "SST-DBT012",
        Severity.WARNING,
        "Duplicate source name or source.table pair",
        "source '{value}' is declared more than once",
        "rename one of them",
    ),
    spec(
        "SST-DBT013",
        Severity.ERROR,
        "Model node has no name",
        "dbt node {value} has no name and was skipped",
        "report this against dbt; a named node is a manifest invariant",
    ),
    spec(
        "SST-DBT014",
        Severity.ERROR,
        "Model node has no database or schema",
        "model '{model}' has empty {key}",
        "set database and schema for this target in profiles.yml or dbt_project.yml",
    ),
    spec(
        "SST-DBT015",
        Severity.ERROR,
        "Model checksum absent on both sides of a comparison",
        "model '{model}' has no checksum; change detection is unusable",
        "check that the dbt installation populates checksum.checksum",
    ),
    spec("SST-DBT016", Severity.INFO, "Model to artifact fan-out", "model '{model}' feeds {count} artifacts", None),
    spec(
        "SST-DBT017",
        Severity.ERROR,
        "dbt manifest schema version is unsupported",
        "manifest schema '{found}'; supported: {expected}",
        "upgrade or downgrade dbt to a version that emits a supported schema, or pass "
        "--allow-unsupported-manifest-schema",
    ),
    spec(
        "SST-DBT018",
        Severity.ERROR,
        "dbt manifest schema version key is absent or unparseable",
        "manifest schema version is {found}",
        "check the dbt version; pass --allow-unsupported-manifest-schema only if you accept the risk",
    ),
    spec("SST-DBT019", Severity.ERROR, "dbt profile could not be parsed", "{path}: {detail}", "fix profiles.yml"),
    spec(
        "SST-DBT020",
        Severity.WARNING,
        "dbt installation type could not be determined",
        "dbt type detection returned {found}",
        "ignore this if a valid manifest exists; the manifest is the contract",
    ),
    spec(
        "SST-DBT021",
        Severity.ERROR,
        "auto_compile requested under an installation that cannot compile a non-default target",
        "defer.auto_compile is true under {found}",
        "pass --manifest with a manifest built for the target instead",
    ),
    spec(
        "SST-DBT022",
        Severity.ERROR,
        "model-paths is unreadable and defaulted",
        "model-paths could not be read; defaulted to {expected}",
        "declare model-paths explicitly as a list of directories",
    ),
    spec(
        "SST-DBT023",
        Severity.WARNING,
        "dbt model referenced with no tests at all",
        "model '{model}' has no tests",
        "add at least a uniqueness test on the declared grain",
    ),
    spec(
        "SST-DBT024",
        Severity.WARNING,
        "dbt model feeding an artifact has no contract",
        "model '{model}' has no contract",
        "add an enforced contract to the model",
    ),
    spec("SST-DBT025", Severity.INFO, "dbt seam summary", "{value}", None),
    spec(
        "SST-DBT026",
        Severity.ERROR,
        "dbt packages are not installed",
        "{count} package(s) in packages.yml are not installed",
        "run dbt deps",
    ),
    spec(
        "SST-DBT027",
        Severity.ERROR,
        "dbt could not be invoked",
        "dbt could not be executed: {detail}",
        "install dbt, or pass --manifest to read a manifest that already exists",
    ),
    spec(
        "SST-DBT028",
        Severity.ERROR,
        "`dbt parse` exited non-zero",
        "dbt parse exited {found}",
        "read dbt's own output above; the failure is in the dbt project",
    ),
    spec(
        "SST-DBT029",
        Severity.ERROR,
        "`dbt parse` reported success but wrote no manifest",
        "dbt parse exited 0 and {path} was not written",
        "check --project-dir and dbt's target-path; dbt wrote its manifest elsewhere",
    ),
    spec(
        "SST-DBT030",
        Severity.ERROR,
        "Forbidden `meta.sst` location key",
        "model '{model}': meta.sst.{key} is forbidden -- delete it",
        "delete the key; relation location comes from dbt's resolved manifest",
    ),
    spec(
        "SST-DBT031",
        Severity.WARNING,
        "Model has no relation to enrich",
        "model '{model}' has no relation, so sst enrich has no columns to read",
        "materialize the model as a table or a view; an ephemeral model has nothing to enrich",
    ),
    spec(
        "SST-DBT032",
        Severity.ERROR,
        "Key metadata is written in the 0.3 form",
        "model '{model}': meta.sst.{field} is written in the 0.3 form",
        "write primary_key as a list of columns and unique_keys as a list of column lists",
    ),
)
