"""Loading codes (LOD): file bytes, YAML syntax, document shape, template syntax, and sidecars."""

from __future__ import annotations

from snowflake_semantic_tools.domain.diagnostics.core import ErrorSpec, Severity, spec

TITLE: str = "Loading"

SPECS: tuple[ErrorSpec, ...] = (
    spec(
        "SST-LOD001",
        Severity.ERROR,
        "YAML syntax error",
        "{file}:{line}:{col}: {detail}",
        "fix the YAML syntax at the reported position",
        condition="yaml.safe_load raises; line and column come from the marker",
    ),
    spec(
        "SST-LOD002",
        Severity.ERROR,
        "Document root is not a mapping",
        "{file} root is {found}, expected a mapping",
        "make the document a top-level mapping",
        condition="the parsed root is a list, scalar or null",
    ),
    spec(
        "SST-LOD003",
        Severity.WARNING,
        "File is empty",
        "{file} is empty",
        "add content, or delete the file",
        condition="the file has zero bytes, or parses to None",
    ),
    spec(
        "SST-LOD004",
        Severity.ERROR,
        "Template expression is malformed",
        "{file}:{line}:{col}: malformed template: {reason}",
        "close the `}}`, or remove the nested `{{`",
        condition="an unterminated or nested `{{ }}`",
        note=(
            "Not an unquoted `{{`: unquoted is the majority spelling and is not valid YAML, so it is "
            "neutralised at the load boundary rather than rejected."
        ),
    ),
    spec(
        "SST-LOD005",
        Severity.ERROR,
        "Duplicate key in a YAML mapping",
        "{file}:{line}: duplicate key '{key}'",
        "remove one of the two keys",
        condition="a mapping declares one key twice; the later silently wins in stock YAML",
    ),
    spec(
        "SST-LOD006",
        Severity.ERROR,
        "File is not valid UTF-8",
        "{file}: invalid UTF-8 at byte {offset}",
        "re-save the file as UTF-8",
        condition="decoding fails",
    ),
    spec(
        "SST-LOD007",
        Severity.ERROR,
        "File exceeds the size limit",
        "{file} is {size} bytes, over the {expected} limit",
        "split the file",
        condition="a candidate file is larger than the configured cap",
    ),
    spec(
        "SST-LOD008",
        Severity.ERROR,
        "Multi-document YAML stream",
        "{file} contains {count} documents",
        "keep one document per file",
        condition="the file uses --- separators",
    ),
    spec(
        "SST-LOD009",
        Severity.ERROR,
        "Unquoted colon inside a plain scalar",
        "{file}:{line}: '{key}' value contains an unquoted ':'",
        "quote the value",
        condition="a description or prose value contains a bare colon-space",
    ),
    spec(
        "SST-LOD010",
        Severity.ERROR,
        "Tab character used for indentation",
        "{file}:{line}: tab used for indentation",
        "indent with spaces",
        condition="YAML forbids tabs in indentation",
    ),
    spec(
        "SST-LOD011",
        Severity.WARNING,
        "Folded scalar used for a multi-line value",
        "{file}:{line}: '{key}' uses a folded scalar",
        "use |- so line breaks survive",
        condition="a multi-line value uses > or >-, which reflows the text",
    ),
    spec(
        "SST-LOD012",
        Severity.WARNING,
        "Trailing whitespace or CRLF line endings",
        "{file}: {detail}",
        "run sst format",
        condition="the file is not canonically formatted at byte level",
    ),
    spec(
        "SST-LOD013",
        Severity.ERROR,
        "Anchor or alias used",
        "{file}:{line}: YAML anchors are not supported",
        "expand the anchor",
        condition="the document uses & or *",
    ),
    spec(
        "SST-LOD014",
        Severity.ERROR,
        "Merge key used",
        "{file}:{line}: merge keys are not supported",
        "expand the merge",
        condition="the document uses <<:",
    ),
    spec(
        "SST-LOD015",
        Severity.ERROR,
        "Non-string mapping key",
        "{file}:{line}: mapping key {found} is not a string",
        "quote the key",
        condition="a key parses to an int, bool, date or null",
    ),
    spec(
        "SST-LOD016",
        Severity.WARNING,
        "Implicit boolean or null coercion",
        "{file}:{line}: '{key}' value {found} coerced to {expected}",
        "quote the value if it is meant as a string, or write {} if it is meant as an empty block",
        condition="YAML 1.1 coerces yes, no, on, off, ~ or an empty value, where null has no documented meaning",
    ),
    spec(
        "SST-LOD017",
        Severity.ERROR,
        "Byte-order mark present",
        "{file} begins with a BOM",
        "re-save without a BOM",
        condition="the file starts with U+FEFF",
    ),
    spec(
        "SST-LOD018",
        Severity.ERROR,
        "Sidecar file referenced by a document is missing",
        "{file} references {path}, which does not exist",
        "create the file, or correct the path",
        condition="a file(), body_file or sql_file path does not resolve at load",
    ),
    spec(
        "SST-LOD019",
        Severity.ERROR,
        "Sidecar file is empty",
        "{path}, referenced by {file}, is empty",
        "add content, or remove the reference",
        condition="a referenced sidecar resolves and has zero bytes",
    ),
    spec(
        "SST-LOD020",
        Severity.WARNING,
        "Unrecognised file extension accepted",
        "{file} uses '{found}'",
        "standardise on .yml",
        condition="a candidate file uses a tolerated but non-canonical extension",
    ),
    spec(
        "SST-LOD021",
        Severity.ERROR,
        "Document declares no recognised root key",
        "{file} declares no recognised root key",
        "add the artifact's root key",
        condition="the root mapping has keys, none of which any type claims",
    ),
    spec(
        "SST-LOD200",
        Severity.INFO,
        ".yaml extension accepted",
        "{file} uses .yaml; accepted",
        None,
        condition="a .yaml file was loaded",
    ),
    spec(
        "SST-LOD201",
        Severity.INFO,
        "File loaded from cache",
        "{file} served from the load cache",
        None,
        condition="the file digest is unchanged since the last run",
    ),
    spec(
        "SST-LOD202",
        Severity.INFO,
        "Line-ending normalisation applied on read",
        "{file} normalised {count} line endings on read",
        None,
        condition="CRLF was normalised in memory, leaving the file untouched",
    ),
)
