"""Planning codes (PLN): observation, preflight, ownership, drift, order, prune, smoke, and --partial."""

from __future__ import annotations

from snowflake_semantic_tools.domain.diagnostics.core import ErrorSpec, Severity, spec

TITLE: str = "Planning"

SPECS: tuple[ErrorSpec, ...] = (
    spec(
        "SST-PLN001",
        Severity.ERROR,
        "Observation query failed",
        "observation of {value} failed: {detail}",
        "check the connection and the role, then re-run plan",
    ),
    spec(
        "SST-PLN002",
        Severity.ERROR,
        "An object of a different type exists at the target name",
        "{artifact}: {value} exists as a {found}",
        "rename the artifact, or drop the existing object",
    ),
    spec(
        "SST-PLN003",
        Severity.WARNING,
        "Prune candidate has no ownership marker",
        "{value} has no SST ownership marker; skipped",
        "adopt it explicitly, or delete it by hand",
    ),
    spec(
        "SST-PLN004",
        Severity.WARNING,
        "Marked prune candidate is absent from local state",
        "{value} carries an SST marker and is absent from state; skipped",
        "reconcile state, or delete it by hand",
    ),
    spec(
        "SST-PLN005",
        Severity.ERROR,
        "Dependency cycle among artifacts",
        "artifact dependency cycle: {cycle}",
        "break the cycle",
    ),
    spec(
        "SST-PLN006",
        Severity.WARNING,
        "Impact-scoped plan requested with no previous manifest",
        "no previous manifest; a full plan was computed",
        "commit the manifest, or pass --state",
    ),
    spec(
        "SST-PLN007",
        Severity.ERROR,
        "Referenced object does not exist in the target",
        "{artifact} references {value}, absent from target '{target}'",
        "publish it first, or correct the reference",
    ),
    spec(
        "SST-PLN008",
        Severity.ERROR,
        "Deploying role lacks a required privilege",
        "{value} lacks {detail} on {target}",
        "grant the privilege",
    ),
    spec(
        "SST-PLN009",
        Severity.WARNING,
        "An object already exists at the target name",
        "{artifact}: {value} already exists",
        "use or_replace, or choose another name",
    ),
    spec(
        "SST-PLN010",
        Severity.ERROR,
        "Target schema does not exist",
        "schema {value} does not exist or is not authorised",
        "create the schema, or correct the target",
    ),
    spec(
        "SST-PLN011",
        Severity.ERROR,
        "Target database does not exist",
        "database {value} does not exist or is not authorised",
        "create the database, or correct the target",
    ),
    spec(
        "SST-PLN012",
        Severity.ERROR,
        "Warehouse does not exist or is not authorised",
        "warehouse {value} does not exist or is not authorised",
        "grant USAGE, or name an existing warehouse",
    ),
    spec(
        "SST-PLN013",
        Severity.WARNING,
        "Live object carries grants that a replace would drop",
        "{artifact}: {count} explicit grants exist on {value}",
        "confirm COPY GRANTS is emitted before applying",
    ),
    spec(
        "SST-PLN014",
        Severity.WARNING,
        "Live definition differs from the last recorded state",
        "{artifact} was changed out of band",
        "review the difference before applying",
    ),
    spec("SST-PLN015", Severity.INFO, "No change for an artifact", "{artifact}: NOOP", None),
    spec("SST-PLN016", Severity.INFO, "Plan summary", "{value}", None),
    spec(
        "SST-PLN017",
        Severity.WARNING,
        "Prune would remove an object a consumer references by name",
        "{value} is referenced outside this project",
        "exclude it from prune, or migrate the consumer",
    ),
    spec(
        "SST-PLN018",
        Severity.ERROR,
        "Plan computed against a stale observation",
        "observation for {value} is {detail}",
        "re-run plan",
    ),
    spec(
        "SST-PLN019",
        Severity.WARNING,
        "Concurrent DDL detected on the target",
        "{value} is being modified by another session",
        "retry, or serialise the publishers",
    ),
    spec(
        "SST-PLN020",
        Severity.ERROR,
        "Smoke query could not be constructed",
        "{artifact}: no smoke query can be built for metric '{member}'",
        "make the metric selectable, or exclude it from smoke checks",
    ),
    spec(
        "SST-PLN021",
        Severity.WARNING,
        "Prune reconciliation found objects the repo does not declare",
        "{count} objects in {value} are not declared here",
        "adopt or delete them explicitly",
    ),
    spec(
        "SST-PLN022",
        Severity.ERROR,
        "Change order is not computable",
        "change order could not be computed: {detail}",
        "resolve the dependency conflict",
    ),
    spec(
        "SST-PLN023",
        Severity.WARNING,
        "Declared name differs from the live object only by case",
        "{artifact}: declared '{value}', live object is '{found}'",
        "normalise the declaration to the rendered case",
    ),
    spec(
        "SST-PLN024",
        Severity.ERROR,
        "Existing object is not managed by SST",
        "{artifact}: {value} exists without trusted SST ownership",
        "adopt or remove the object explicitly before applying",
        demotable=False,
    ),
    spec(
        "SST-PLN025",
        Severity.ERROR,
        "Artifact target moved",
        "{artifact}: recorded target '{found}' differs from declared target '{expected}'",
        "move the object explicitly, then reconcile state and re-run plan",
        demotable=False,
    ),
    spec(
        "SST-PLN026",
        Severity.ERROR,
        "Stage is not an internal SSE stage",
        "{artifact}: stage {value} is {found}, expected INTERNAL NO CSE",
        "point the configuration at an internal stage with SNOWFLAKE_SSE encryption; SST never alters a stage",
        demotable=False,
    ),
    spec(
        "SST-PLN027",
        Severity.ERROR,
        "Version alias holds different content",
        "{artifact}: version alias {value} holds files that differ from the bundle ({detail})",
        "an earlier publish left a damaged version under this alias; remove the alias in Snowflake, then plan again",
        demotable=False,
    ),
    spec(
        "SST-PLN028",
        Severity.ERROR,
        "Registry row changed since SST last wrote it",
        "{artifact}: registry row '{value}' has VERSION {found}, and SST last wrote {expected}",
        "another writer changed the row; reconcile it, then plan again",
        demotable=False,
    ),
    spec(
        "SST-PLN029",
        Severity.ERROR,
        "Registry table has the wrong shape",
        "{artifact}: {value} {detail}",
        "SST never alters the registry; fix the table or point skills.stage at a compatible one",
        demotable=False,
    ),
    spec(
        "SST-PLN030",
        Severity.ERROR,
        "Pinned version is not part of this plan",
        "{artifact}: pins the published version of {value}; select {value} as well",
        "plan the pinned artifact in the same run; when its version is already published it plans as NOOP",
        demotable=False,
    ),
    spec(
        "SST-PLN032",
        Severity.INFO,
        "Excluded from a partial run",
        "{artifact} has errors, or depends on something that does, so this partial run leaves it unpublished",
        "fix the errors reported for it; what is live stays as it is, and state keeps its record",
    ),
    spec(
        "SST-PLN033",
        Severity.INFO,
        "Partial run cannot go ahead",
        "--partial publishes nothing: {found} on {value} cannot be traced to the artifacts it would change",
        "fix that error first; a configuration error, or an error in a semantic view member such as a metric, "
        "stops every run, because the views it belongs to would otherwise publish without it",
    ),
    spec(
        "SST-PLN034",
        Severity.INFO,
        "Prune is report-only",
        "{artifact} is no longer declared; SST never removes {value}: {detail}",
        (
            "the plan lists it until the objects are removed by hand; it is never a write, and the plan exits 2 only "
            "until an apply records it"
        ),
    ),
    spec(
        "SST-PLN100",
        Severity.ERROR,
        "Smoke query failed",
        "{artifact}: smoke query for metric '{member}' failed: {detail}",
        "fix the metric; a created view is not a working view",
    ),
    spec("SST-PLN101", Severity.INFO, "Smoke check skipped", "{artifact}: smoke check skipped ({detail})", None),
    spec(
        "SST-PLN900",
        Severity.ERROR,
        "Change order is not a valid topological order",
        "change order violates {value}",
        "report this as a bug",
    ),
)
