"""Planning codes (PLN): observation, preflight, ownership, drift, order, prune, smoke, and --partial."""

from __future__ import annotations

from snowflake_semantic_tools.domain.diagnostics.core import ErrorSpec, Severity, spec

TITLE: str = "Planning"

SPECS: tuple[ErrorSpec, ...] = (
    spec(
        "SST-PLN001",
        Severity.ERROR,
        "Observation query failed",
        "observation of {value} failed: {detail}",
        "check the connection and the role, then re-run plan",
        condition="a query that reads current state failed",
    ),
    spec(
        "SST-PLN002",
        Severity.ERROR,
        "An object of a different type exists at the target name",
        "{artifact}: {value} exists as a {found}",
        "rename the artifact, or drop the existing object",
        condition="the target name is occupied by another object kind",
    ),
    spec(
        "SST-PLN003",
        Severity.WARNING,
        "Prune candidate has no ownership marker",
        "{value} has no SST ownership marker; skipped",
        "adopt it explicitly, or delete it by hand",
        condition="an unmanaged object sits in the target schema",
    ),
    spec(
        "SST-PLN004",
        Severity.WARNING,
        "Marked prune candidate is absent from local state",
        "{value} carries an SST marker and is absent from state; skipped",
        "reconcile state, or delete it by hand",
        condition="a marked object has no local record",
    ),
    spec(
        "SST-PLN005",
        Severity.ERROR,
        "Dependency cycle among artifacts",
        "artifact dependency cycle: {cycle}",
        "break the cycle",
        condition="the artifact-level dependency graph is not acyclic",
    ),
    spec(
        "SST-PLN006",
        Severity.WARNING,
        "Impact-scoped plan requested with no previous manifest",
        "no previous manifest; a full plan was computed",
        "commit the manifest, or pass --state",
        condition="impact scoping is unavailable",
    ),
    spec(
        "SST-PLN007",
        Severity.ERROR,
        "Referenced object does not exist in the target",
        "{artifact} references {value}, absent from target '{target}'",
        "publish it first, or correct the reference",
        condition="an observation shows a referenced object is missing",
    ),
    spec(
        "SST-PLN008",
        Severity.ERROR,
        "Deploying role lacks a required privilege",
        "{value} lacks {detail} on {target}",
        "grant the privilege",
        condition="an observation shows the role cannot perform the planned write",
    ),
    spec(
        "SST-PLN009",
        Severity.WARNING,
        "An object already exists at the target name",
        "{artifact}: {value} already exists",
        "use or_replace, or choose another name",
        condition="the planned create would collide with an existing object",
    ),
    spec(
        "SST-PLN010",
        Severity.ERROR,
        "Target schema does not exist",
        "schema {value} does not exist or is not authorised",
        "create the schema, or correct the target",
        condition="the target schema is absent from the observation",
    ),
    spec(
        "SST-PLN011",
        Severity.ERROR,
        "Target database does not exist",
        "database {value} does not exist or is not authorised",
        "create the database, or correct the target",
        condition="the target database is absent from the observation",
    ),
    spec(
        "SST-PLN012",
        Severity.ERROR,
        "Warehouse does not exist or is not authorised",
        "warehouse {value} does not exist or is not authorised",
        "grant USAGE, or name an existing warehouse",
        condition="the configured warehouse is unusable",
    ),
    spec(
        "SST-PLN013",
        Severity.WARNING,
        "Live object carries grants that a replace would drop",
        "{artifact}: {count} explicit grants exist on {value}",
        "confirm COPY GRANTS is emitted before applying",
        condition="plan surfaces what is at stake before a replace",
    ),
    spec(
        "SST-PLN014",
        Severity.WARNING,
        "Live definition differs from the last recorded state",
        "{artifact} was changed out of band",
        "review the difference before applying",
        condition="an out-of-band edit is detectable from the marker",
    ),
    spec(
        "SST-PLN015",
        Severity.INFO,
        "No change for an artifact",
        "{artifact}: NOOP",
        None,
        condition="the proposed definition matches the observation",
    ),
    spec(
        "SST-PLN016",
        Severity.INFO,
        "Plan summary",
        "{value}",
        None,
        condition="per-type counts of create, replace, noop and prune",
    ),
    spec(
        "SST-PLN017",
        Severity.WARNING,
        "Prune would remove an object a consumer references by name",
        "{value} is referenced outside this project",
        "exclude it from prune, or migrate the consumer",
        condition="a prune candidate is named by something SST does not manage",
        note="What names an object is read from `SNOWFLAKE.ACCOUNT_USAGE.OBJECT_DEPENDENCIES`, "
        "which needs IMPORTED PRIVILEGES on the `SNOWFLAKE` database and lags by up to three hours. "
        "A role without it skips this check for each prune candidate, reported as `SST-VAL020`, "
        "and the prune goes ahead: this is a warning, never what stops a prune.",
    ),
    spec(
        "SST-PLN018",
        Severity.ERROR,
        "Plan computed against a stale observation",
        "observation for {value} is {detail}",
        "re-run plan",
        condition="observing and planning in one run took longer than the 15-minute observation lifetime",
    ),
    spec(
        "SST-PLN019",
        Severity.WARNING,
        "Concurrent DDL detected on the target",
        "{value} is being modified by another session",
        "retry, or serialise the publishers",
        condition="the observation shows a competing writer",
        note="Reading other sessions' locks needs MONITOR on the account. A role without it skips "
        "this check, reported as `SST-VAL020`, and the plan goes ahead.",
    ),
    spec(
        "SST-PLN020",
        Severity.ERROR,
        "Smoke query could not be constructed",
        "{artifact}: no smoke query can be built for metric '{member}'",
        "make the metric selectable, or exclude it from smoke checks",
        condition="a public metric cannot be expressed as a query",
    ),
    spec(
        "SST-PLN021",
        Severity.WARNING,
        "Prune reconciliation found objects the repo does not declare",
        "{count} objects in {value} are not declared here",
        "adopt or delete them explicitly",
        condition="the declared set and the live set differ after case folding",
    ),
    spec(
        "SST-PLN022",
        Severity.ERROR,
        "Change order is not computable",
        "change order could not be computed: {detail}",
        "resolve the dependency conflict",
        condition="topological ordering failed for a reason other than a cycle",
    ),
    spec(
        "SST-PLN023",
        Severity.WARNING,
        "Declared name differs from the live object only by case",
        "{artifact}: declared '{value}', live object is '{found}'",
        "normalise the declaration to the rendered case",
        condition="an unquoted declared identifier matches a live object only after case folding",
    ),
    spec(
        "SST-PLN024",
        Severity.ERROR,
        "Existing object is not managed by SST",
        "{artifact}: {value} exists without trusted SST ownership",
        "adopt or remove the object explicitly before applying",
        demotable=False,
        condition="an object holds the target name and state records no SST entry for it",
    ),
    spec(
        "SST-PLN025",
        Severity.ERROR,
        "Artifact target moved",
        "{artifact}: recorded target '{found}' differs from declared target '{expected}'",
        "move the object explicitly, then reconcile state and re-run plan",
        demotable=False,
        condition="state records the artifact (or its resources) at a target other than the one declared",
    ),
    spec(
        "SST-PLN026",
        Severity.ERROR,
        "Stage is not an internal SSE stage",
        "{artifact}: stage {value} is {found}, expected INTERNAL NO CSE",
        "point the configuration at an internal stage with SNOWFLAKE_SSE encryption; SST never alters a stage",
        demotable=False,
        condition="the bundle or profile stage is not INTERNAL with SNOWFLAKE_SSE encryption",
    ),
    spec(
        "SST-PLN027",
        Severity.ERROR,
        "Version alias holds different content",
        "{artifact}: version alias {value} holds files that differ from the bundle ({detail})",
        "an earlier publish left a damaged version under this alias; remove the alias in Snowflake, then plan again",
        demotable=False,
        condition="a version alias SST would reuse holds files that differ from the bundle",
    ),
    spec(
        "SST-PLN028",
        Severity.ERROR,
        "Registry row changed since SST last wrote it",
        "{artifact}: registry row '{value}' has VERSION {found}, and SST last wrote {expected}",
        "another writer changed the row; reconcile it, then plan again",
        demotable=False,
        condition="a profile-registry row carries a VERSION neither state nor this release names",
    ),
    spec(
        "SST-PLN029",
        Severity.ERROR,
        "Registry table has the wrong shape",
        "{artifact}: {value} {detail}",
        "SST never alters the registry; fix the table or point skills.stage at a compatible one",
        demotable=False,
        condition="the profile registry table lacks a column SST writes, or types it differently",
    ),
    spec(
        "SST-PLN030",
        Severity.ERROR,
        "Pinned version is not part of this plan",
        "{artifact}: pins the published version of {value}; select {value} as well",
        "plan the pinned artifact in the same run; when its version is already published it plans as NOOP",
        demotable=False,
        condition="a create or update pins the published version of an artifact this plan leaves out",
    ),
    spec(
        "SST-PLN032",
        Severity.INFO,
        "Excluded from a partial run",
        "{artifact} has errors, or depends on something that does, so this partial run leaves it unpublished",
        "fix the errors reported for it; what is live stays as it is, and state keeps its record",
        condition="under --partial, an artifact with errors (or depending on one) is left out of the plan",
    ),
    spec(
        "SST-PLN033",
        Severity.INFO,
        "Partial run cannot go ahead",
        "--partial publishes nothing: {found} on {value} cannot be traced to the artifacts it would change",
        "fix that error first; a configuration error, or an error in a semantic view member such as a metric, "
        "stops every run, because the views it belongs to would otherwise publish without it",
        condition=("under --partial, an error names no artifact, so nothing can be excluded and the run stops"),
    ),
    spec(
        "SST-PLN034",
        Severity.INFO,
        "Prune is report-only",
        "{artifact} is no longer declared; SST never removes {value}: {detail}",
        "the plan lists it until the objects are removed by hand; it is never a write, and the plan exits 2 only "
        "until an apply records it",
        condition=(
            "an artifact recorded in state is no longer declared; prune reports the resources SST "
            "keeps and never executes"
        ),
    ),
    spec(
        "SST-PLN100",
        Severity.ERROR,
        "Smoke query failed",
        "{artifact}: smoke query for metric '{member}' failed: {detail}",
        "fix the metric; a created view is not a working view",
        condition=("a smoke probe of a metric failed (`sst test --suite smoke`); any other probe reports `SST-APL100`"),
    ),
    spec(
        "SST-PLN101",
        Severity.INFO,
        "Smoke check skipped",
        "{artifact}: smoke check skipped ({detail})",
        None,
        condition="smoke queries are disabled, or no connection was available",
    ),
    spec(
        "SST-PLN900",
        Severity.ERROR,
        "Change order is not a valid topological order",
        "change order violates {value}",
        "report this as a bug",
        condition="the computed order places a dependent before its dependency",
    ),
)
