"""Parsing codes (PRS): a file or field that does not have the shape, type, or value SST accepts."""

from __future__ import annotations

from snowflake_semantic_tools.domain.diagnostics.core import ErrorSpec, Severity, spec

TITLE: str = "Parsing"

SPECS: tuple[ErrorSpec, ...] = (
    spec(
        "SST-PRS001",
        Severity.WARNING,
        "Unknown top-level key",
        "no registered type owns root key '{key}'",
        "remove the block, or register a type that owns it",
    ),
    spec(
        "SST-PRS002",
        Severity.ERROR,
        "Required field missing",
        "{artifact}: required field '{field}' is missing",
        "add {field}",
    ),
    spec(
        "SST-PRS003",
        Severity.ERROR,
        "Field has the wrong type",
        "{artifact}: '{field}' expects {expected}, found {found}",
        "change the value to {expected}",
    ),
    spec(
        "SST-PRS004",
        Severity.WARNING,
        "Unknown field in a known block",
        "{artifact}: unknown field '{field}'",
        "remove the field, or check the spelling",
    ),
    spec(
        "SST-PRS005",
        Severity.ERROR,
        "Name is not a valid identifier",
        "{artifact}: '{value}' is not a valid identifier",
        "use letters, digits and underscores, starting with a letter",
    ),
    spec(
        "SST-PRS006",
        Severity.ERROR,
        "Duplicate name within a type",
        "{type} '{name}' is declared more than once",
        "rename one of them",
    ),
    spec(
        "SST-PRS007",
        Severity.ERROR,
        "Name is not unique across the artifact set",
        "{type} '{name}' collides with {other}",
        "rename one of them",
    ),
    spec(
        "SST-PRS008",
        Severity.ERROR,
        "Name collides with a derived member name",
        "metric '{name}' collides with a derived metric name",
        "rename one of them",
    ),
    spec(
        "SST-PRS009",
        Severity.ERROR,
        "Name is not a valid tool identifier",
        "'{name}' does not resolve to a 1-64 char tool identifier",
        "shorten or simplify the name",
    ),
    spec(
        "SST-PRS010",
        Severity.ERROR,
        "Identifier exceeds the object name limit",
        "'{name}' is {size} chars, over the {expected} limit",
        "shorten the name",
    ),
    spec(
        "SST-PRS011",
        Severity.ERROR,
        "Identifier requires quoting and quoting is not declared",
        "'{name}' needs quoting to render safely",
        "rename it, or declare it quoted",
    ),
    spec(
        "SST-PRS012",
        Severity.WARNING,
        "Non-ASCII identifier",
        "'{name}' contains non-ASCII characters",
        "use ASCII identifiers",
    ),
    spec(
        "SST-PRS013",
        Severity.ERROR,
        "Value outside the allowed set for a closed field",
        "{artifact}: '{field}' is '{found}', expected one of {expected}",
        "use one of {expected}",
    ),
    spec(
        "SST-PRS014",
        Severity.ERROR,
        "Mutually exclusive fields both present",
        "{artifact}: '{field}' and '{other}' are mutually exclusive",
        "declare exactly one",
    ),
    spec(
        "SST-PRS015",
        Severity.ERROR,
        "Paired fields not declared together",
        "{artifact}: '{field}' requires '{other}'",
        "declare both, or neither",
    ),
    spec(
        "SST-PRS016",
        Severity.ERROR,
        "Numeric value out of range",
        "{artifact}: '{field}' is {found}, expected {expected}",
        "use a value in {expected}",
    ),
    spec(
        "SST-PRS017",
        Severity.ERROR,
        "Unparseable timestamp",
        "{artifact}: '{field}' value '{found}' is not an epoch or ISO timestamp",
        "use an integer epoch or an ISO-8601 string",
    ),
    spec(
        "SST-PRS018",
        Severity.ERROR,
        "Collection element has the wrong shape",
        "{artifact}: '{field}'[{index}] expects {expected}, found {found}",
        "correct the element",
    ),
    spec(
        "SST-PRS019",
        Severity.ERROR,
        "Boolean field holds a non-boolean",
        "{artifact}: '{field}' is '{found}', expected a boolean",
        "use true or false",
    ),
    spec(
        "SST-PRS020",
        Severity.WARNING,
        "Deprecated field spelling",
        "{artifact}: '{field}' is deprecated; use '{expected}'",
        "rename the field",
    ),
    spec(
        "SST-PRS021",
        Severity.ERROR,
        "Deprecated relationship column shape",
        "{artifact}: relationship_columns / left_column / right_column is not supported",
        "use relationship_conditions",
    ),
    spec(
        "SST-PRS022",
        Severity.ERROR,
        "Unknown field within edit distance of a known field",
        "{artifact}: unknown field '{field}'; did you mean '{expected}'?",
        "correct the spelling",
    ),
    spec(
        "SST-PRS023",
        Severity.ERROR,
        "Passthrough block collides with a modelled key",
        "{artifact}: passthrough key '{key}' is already rendered by SST",
        "remove the key from passthrough",
    ),
    spec(
        "SST-PRS024",
        Severity.WARNING,
        "Passthrough block is non-empty",
        "{artifact}: {count} passthrough keys will be rendered unvalidated",
        "promote the keys to first-class fields where possible",
    ),
    spec(
        "SST-PRS025",
        Severity.ERROR,
        "Reserved alias used",
        "{artifact}: alias '{value}' is reserved",
        "choose a different alias",
    ),
    spec(
        "SST-PRS026",
        Severity.ERROR,
        "Tag value exceeds the length limit",
        "{artifact}: tag '{field}' value is {size} chars, over 256",
        "shorten the tag value",
    ),
    spec(
        "SST-PRS027",
        Severity.ERROR,
        "Tags block has the wrong shape",
        "{artifact}: tags must be a list of name and value entries, found {found}",
        "correct the tags block",
    ),
    spec(
        "SST-PRS028",
        Severity.ERROR,
        "Constraints block has the wrong shape",
        "{artifact}: constraints block is invalid: {detail}",
        "correct the constraints block",
    ),
    spec(
        "SST-PRS029",
        Severity.ERROR,
        "Synonyms block has the wrong type",
        "{artifact}: synonyms must be a list of strings, found {found}",
        "use a list of strings",
    ),
    spec(
        "SST-PRS030",
        Severity.WARNING,
        "Synonym contains problematic characters",
        "{artifact}: synonym '{value}' contains {detail}",
        "remove the punctuation",
    ),
    spec(
        "SST-PRS031",
        Severity.WARNING,
        "Name collides with a reserved word",
        "'{name}' is a reserved word",
        "rename it, or accept the quoted identifier",
    ),
    spec(
        "SST-PRS032",
        Severity.ERROR,
        "Input schema property has a forbidden type",
        "{artifact}: input_schema property '{field}' has type '{found}'",
        "use string, number, integer, boolean or array",
    ),
    spec(
        "SST-PRS033",
        Severity.ERROR,
        "Required input-schema name is not a declared property",
        "{artifact}: input_schema.required names '{field}', absent from properties",
        "declare the property, or drop it from required",
    ),
    spec(
        "SST-PRS034",
        Severity.ERROR,
        "Frontmatter missing a required key",
        "{artifact}: SKILL.md frontmatter omits '{field}'",
        "declare name and description in the frontmatter",
    ),
    spec(
        "SST-PRS100",
        Severity.WARNING,
        "Name collides with a reserved identifier namespace",
        "'{name}' is in a reserved namespace",
        "rename it",
    ),
    spec(
        "SST-PRS101",
        Severity.ERROR,
        "Required collection is empty",
        "{artifact}: '{field}' is present and empty",
        "declare at least one entry, or remove the key",
    ),
    spec(
        "SST-PRS102",
        Severity.ERROR,
        "tables is explicitly empty",
        "{artifact}: 'tables: []' is not accepted",
        "declare the tables the member attaches to",
        demotable=False,
    ),
    spec(
        "SST-PRS103",
        Severity.ERROR,
        "Value outside the allowed enum",
        "{artifact}: '{field}' is '{found}', expected one of {expected}",
        "use one of {expected}",
    ),
    spec(
        "SST-PRS104",
        Severity.ERROR,
        "Member declared under two owners",
        "{member} is declared under both {a} and {b}",
        "declare it once",
    ),
    spec(
        "SST-PRS105",
        Severity.ERROR,
        "Member type not accepted by its owner",
        "{type} does not accept members of type {member_type}",
        "move the member",
    ),
    spec(
        "SST-PRS106",
        Severity.ERROR,
        "Duplicate member name within an owner",
        "{artifact}: {member_type} '{name}' is declared twice",
        "rename one of them",
    ),
    spec(
        "SST-PRS107",
        Severity.ERROR,
        "Member declares no distinguishing key",
        "{artifact}: {member_type} entry {index} has no name",
        "name the member",
    ),
    spec(
        "SST-PRS109",
        Severity.ERROR,
        "table_config names a table not in tables",
        "{artifact}: table_config key '{name}' is not in tables:",
        "remove the entry, or add the table",
    ),
    spec(
        "SST-PRS110",
        Severity.ERROR,
        "Condition does not parse to one column pair",
        "{artifact}: condition '{value}' does not parse to one left/right pair",
        "express one pair per condition",
    ),
    spec(
        "SST-PRS111",
        Severity.ERROR,
        "Range condition names one column twice",
        "{artifact}: range condition uses '{name}' for both start and end",
        "name two different columns",
    ),
    spec(
        "SST-PRS112",
        Severity.ERROR,
        "More than one asof condition",
        "{artifact}: {count} asof conditions declared",
        "declare at most one",
    ),
    spec(
        "SST-PRS113",
        Severity.ERROR,
        "Expression field is not a string",
        "{artifact}: '{field}' expects a SQL string, found {found}",
        "supply the expression as a string",
    ),
    spec(
        "SST-PRS114",
        Severity.ERROR,
        "Score ranges are not contiguous",
        "{artifact}: score_ranges leave a gap or overlap at {value}",
        "make the ranges contiguous with min-inclusive, max-inclusive boundaries",
    ),
    spec(
        "SST-PRS115",
        Severity.ERROR,
        "threshold_default declares no usable bound inside the scale",
        "{artifact}: threshold_default {found} is not a usable bound within max_score {expected}",
        "declare min, optionally max, with min <= max and both inside max_score",
    ),
    spec(
        "SST-PRS116",
        Severity.ERROR,
        "Unsupported template placeholder in a judge prompt",
        "{artifact}: '{placeholder}' is not one of the 12 supported names",
        "use a supported placeholder",
    ),
    spec(
        "SST-PRS117",
        Severity.ERROR,
        "Dataset row has no question or no expected field",
        "{artifact}: row {index} has {detail}",
        "give every row a question and at least one expectation",
    ),
    spec(
        "SST-PRS118",
        Severity.ERROR,
        "Sample question entry is a bare string",
        "{artifact}: sample_questions[{index}] is a string, expected a mapping",
        "use {{question: ...}} maps",
    ),
    spec(
        "SST-PRS119",
        Severity.ERROR,
        "Skill folder contains another skill folder",
        "{artifact}: nested skill folder at {path}",
        "flatten the layout; one skill per folder",
    ),
    spec(
        "SST-PRS120",
        Severity.ERROR,
        "SKILL.md is not at the folder root",
        "{artifact}: SKILL.md found at {path}",
        "move SKILL.md to the folder root",
    ),
    spec(
        "SST-PRS123",
        Severity.ERROR,
        "Semantic view definition is malformed",
        "{artifact}: {detail}",
        "fix the field the message names; the semantic views guide lists each field's form",
    ),
    spec(
        "SST-PRS124",
        Severity.ERROR,
        "Window frame is not a frame clause",
        "{artifact}: window frame '{value}' is not ROWS or RANGE BETWEEN <bound> AND <bound>",
        (
            "write each bound as UNBOUNDED PRECEDING, UNBOUNDED FOLLOWING, CURRENT ROW, or <n> or `INTERVAL '<n> "
            "<unit>'` followed by PRECEDING or FOLLOWING"
        ),
    ),
    spec(
        "SST-PRS125",
        Severity.WARNING,
        "File formatting is not preserved",
        "{file}: writing it changes lines sst enrich did not edit",
        "review the change with sst enrich --dry-run; once the file is written, later runs keep its formatting exactly",
    ),
    spec(
        "SST-PRS900",
        Severity.ERROR,
        "Parser returned a non-frozen record",
        "{type} parser returned {cls}, which is mutable",
        "return a frozen dataclass",
    ),
)
