"""Validation codes 2xx (VAL): relationships -- conditions, endpoints, keys, join paths, and cycles."""

from __future__ import annotations

from snowflake_semantic_tools.domain.diagnostics.core import ErrorSpec, Severity, spec

TITLE: str = "Validation"

SPECS: tuple[ErrorSpec, ...] = (
    spec(
        "SST-VAL201",
        Severity.ERROR,
        "relationship_conditions is empty",
        "relationship '{relationship}' declares no conditions",
        "declare at least one condition",
    ),
    spec(
        "SST-VAL202",
        Severity.ERROR,
        "A declared condition would not be emitted",
        "relationship '{relationship}': condition '{value}' would be dropped from the DDL",
        "fix the condition so it renders, or remove it",
        demotable=False,
    ),
    spec(
        "SST-VAL203",
        Severity.ERROR,
        "Relationship names a table not in the view",
        "relationship '{relationship}' names '{name}', absent from {artifact}",
        "add the table to the view, or drop the relationship",
    ),
    spec(
        "SST-VAL204",
        Severity.ERROR,
        "Join condition column is not on the named table",
        "relationship '{relationship}': '{column}' is not on '{name}'",
        "correct the column, or swap the sides",
    ),
    spec(
        "SST-VAL205",
        Severity.ERROR,
        "Relationship sides never appear together in any view",
        "relationship '{relationship}' joins '{a}' and '{b}', which share no view",
        "add both tables to one view, or drop the relationship",
    ),
    spec(
        "SST-VAL206",
        Severity.ERROR,
        "Range relationship target declares no distinct_range",
        "relationship '{relationship}' is a range join and '{name}' declares no distinct_range",
        "declare distinct_range on the target table",
    ),
    spec(
        "SST-VAL207",
        Severity.ERROR,
        "Self-loop on a single logical table",
        "relationship '{relationship}' joins '{name}' to itself",
        "declare two logical names over the one model",
    ),
    spec(
        "SST-VAL208",
        Severity.WARNING,
        "Equality join to a finer-grained table",
        "relationship '{relationship}' joins '{a}' to '{b}', whose grain is finer than one row per key",
        "use an asof join, or aggregate the target",
    ),
    spec(
        "SST-VAL209",
        Severity.WARNING,
        "Ambiguous join path between two tables",
        "{artifact}: {count} paths between '{a}' and '{b}'",
        "declare using_relationships on the affected metrics",
    ),
    spec(
        "SST-VAL210",
        Severity.WARNING,
        "Join target declares no key covering the join columns",
        "relationship '{relationship}': '{name}' declares neither primary_key nor unique_keys over {value}",
        "declare the key; it is the cheapest fan-out protection",
    ),
    spec(
        "SST-VAL211",
        Severity.WARNING,
        "relationship_type or join_type declared",
        "relationship '{relationship}' declares '{field}', which is not emitted",
        "remove the key",
    ),
    spec(
        "SST-VAL212",
        Severity.WARNING,
        "Declared cardinality disagrees with the data",
        "relationship '{relationship}' declares cardinality {found}; the spot-check found {value}",
        "correct the declaration, or fix the grain",
    ),
    spec(
        "SST-VAL213",
        Severity.ERROR,
        "Multi-column condition is not expressible",
        "relationship '{relationship}': condition '{value}' spans multiple columns per side",
        "split it into one condition per column pair",
    ),
    spec(
        "SST-VAL214",
        Severity.ERROR,
        "using_relationships names an undeclared relationship",
        "metric '{metric}' names relationship '{relationship}', which is not declared",
        "declare the relationship, or correct the name",
    ),
    spec(
        "SST-VAL215",
        Severity.ERROR,
        "Relationship graph has a cycle that changes results",
        "{artifact}: relationship cycle {cycle}",
        "break the cycle, or split into role-playing tables",
    ),
    spec(
        "SST-VAL216",
        Severity.INFO,
        "Inferred many-to-many path through a bridge table",
        "{artifact}: many-to-many path {value} inferred through '{name}'",
        None,
    ),
    spec(
        "SST-VAL217",
        Severity.INFO,
        "Join graph summary",
        "{artifact}: {count} tables, {value}",
        None,
    ),
    spec(
        "SST-VAL218",
        Severity.ERROR,
        "Range join target has overlapping ranges",
        "relationship '{relationship}': '{name}' declares distinct_range over ({a}, {b}) but the ranges overlap, for example {value}",
        "make the ranges disjoint, or narrow the range columns",
    ),
    spec(
        "SST-VAL219",
        Severity.ERROR,
        "A scoped bare column does not exist on its model",
        "{artifact}: table_config.{model}.{field} names column '{column}', which does not exist on {model}",
        "correct the column name, or add it to the dbt model",
    ),
    spec(
        "SST-VAL220",
        Severity.WARNING,
        "A declared view variable is never referenced",
        "{artifact}: variable '{name}' is declared and never used",
        "reference it in an expr, or remove it",
    ),
    spec(
        "SST-VAL221",
        Severity.WARNING,
        "A bare identifier in an expr matches no column and no declared variable",
        "{artifact}: '{name}' in {field} is neither a column nor a declared variable",
        "declare the variable, correct the name, or wrap the column in a two-arg ref",
    ),
    spec(
        "SST-VAL222",
        Severity.ERROR,
        "Dimension declares a private access modifier",
        "{artifact}: dimension '{member}' declares access_modifier '{value}'; SST does not support a private dimension",
        "remove the key",
    ),
    spec(
        "SST-VAL223",
        Severity.ERROR,
        "A primary-key column is also declared unique",
        "{artifact}: column '{column}' on '{model}' appears in both primary_key and unique_keys",
        "remove it from unique_keys -- a primary key is already unique",
    ),
)
