"""Validation codes 5xx (VAL): Cortex Agents.

The live agent a secure or shared spec is published over, the rendered spec's completeness and
size, its tools (names, keys, descriptions, resources, and the objects they resolve to), its
instructions, skill sources, orchestration settings, profile, and versions.
"""

from __future__ import annotations

from snowflake_semantic_tools.domain.diagnostics.core import ErrorSpec, Severity, spec

TITLE: str = "Validation"

SPECS: tuple[ErrorSpec, ...] = (
    spec(
        "SST-VAL506",
        Severity.WARNING,
        "secure: true requires the owner role to round-trip",
        "agent '{artifact}' is secure; the round-trip check needs the owner role",
        "run CI as the owner role, or accept that the round-trip is skipped",
    ),
    spec(
        "SST-VAL507",
        Severity.ERROR,
        "secure: false transition blocked by a share or application role",
        "agent '{artifact}' is granted to {value}; it cannot become non-secure",
        "keep secure: true, or revoke the share grant first",
    ),
    spec(
        "SST-VAL508",
        Severity.ERROR,
        "Tag name does not resolve",
        "agent '{artifact}': tag '{field}' does not resolve to a tag object",
        "create the tag, or correct the name",
    ),
    spec(
        "SST-VAL509",
        Severity.ERROR,
        "Rendered spec differs from the live spec",
        "agent '{artifact}': re-render differs from the live spec at {value}",
        "apply, or reconcile the authored file with the live object",
    ),
    spec(
        "SST-VAL510",
        Severity.ERROR,
        "Renderer emitted a partial spec",
        "agent '{artifact}': rendered spec omits {value}",
        "emit the complete spec; a partial spec deletes fields on the live agent",
        demotable=False,
    ),
    spec(
        "SST-VAL511",
        Severity.ERROR,
        "Rendered spec exceeds the size limit",
        "agent '{artifact}': rendered spec is {size} bytes, over the 100,000 limit",
        "move instructions into referenced files",
    ),
    spec(
        "SST-VAL512",
        Severity.WARNING,
        "Rendered spec is near the size limit",
        "agent '{artifact}': rendered spec is {size} bytes, over 80% of the limit",
        "trim the instruction surface",
    ),
    spec(
        "SST-VAL513",
        Severity.ERROR,
        "Resolved tool name is not 1-64 characters",
        "agent '{artifact}': resolved tool name '{name}' is {size} chars",
        "shorten the source name; for Analyst tools this is the derived name",
    ),
    spec(
        "SST-VAL514",
        Severity.ERROR,
        "Resolved tool names collide case-sensitively",
        "agent '{artifact}': tool name '{name}' is declared twice",
        "rename one of them",
    ),
    spec(
        "SST-VAL515",
        Severity.WARNING,
        "Resolved tool names collide case-insensitively",
        "agent '{artifact}': '{a}' and '{b}' differ only by case",
        "rename one; an eval must match the trace name exactly",
    ),
    spec(
        "SST-VAL516",
        Severity.ERROR,
        "Tool type and key combination is illegal",
        "agent '{artifact}': tool '{name}' of type {found} declares '{key}'",
        "remove the key, or change the tool type",
    ),
    spec(
        "SST-VAL517",
        Severity.ERROR,
        "web_search tool is not named web_search",
        "agent '{artifact}': web_search tool is named '{name}'",
        "rename it to web_search; the trace name is not configurable",
    ),
    spec(
        "SST-VAL518",
        Severity.ERROR,
        "Tool has no description",
        "agent '{artifact}': tool '{name}' has no description",
        "write a description; it is the router",
    ),
    spec(
        "SST-VAL519",
        Severity.WARNING,
        "Two tool descriptions are near-duplicates",
        "agent '{artifact}': '{a}' and '{b}' have near-identical descriptions",
        "differentiate them",
    ),
    spec(
        "SST-VAL520",
        Severity.ERROR,
        "Analyst tool does not declare exactly one semantic view",
        "agent '{artifact}': tool '{name}' declares {count} semantic views",
        "declare exactly one semantic_view and no name",
    ),
    spec(
        "SST-VAL521",
        Severity.ERROR,
        "Cortex Search tool omits a required key",
        "agent '{artifact}': tool '{name}' omits '{field}'",
        "declare search_service and name",
    ),
    spec(
        "SST-VAL522",
        Severity.ERROR,
        "stage_path and relative_path_column not declared together",
        "agent '{artifact}': tool '{name}' declares '{field}' without '{other}'",
        "declare both, or neither; one alone is a silent no-op",
    ),
    spec(
        "SST-VAL523",
        Severity.ERROR,
        "Filter column is not marked filterable",
        "agent '{artifact}': tool '{name}' filters on '{column}', not marked filterable",
        "mark the column filterable: true",
    ),
    spec(
        "SST-VAL524",
        Severity.ERROR,
        "columns_and_descriptions entry is malformed",
        "agent '{artifact}': tool '{name}' column '{column}': {detail}",
        "use type string or datetime, with boolean searchable and filterable",
    ),
    spec(
        "SST-VAL525",
        Severity.WARNING,
        "Searchable column is a vector index column",
        "agent '{artifact}': tool '{name}' marks vector column '{column}' searchable",
        "clear searchable on the vector column",
    ),
    spec(
        "SST-VAL526",
        Severity.ERROR,
        "generic tool declares no object input schema",
        "agent '{artifact}': tool '{name}' input_schema is {found}",
        "declare input_schema with type: object",
    ),
    spec(
        "SST-VAL527",
        Severity.ERROR,
        "generic tool declares no warehouse",
        "agent '{artifact}': tool '{name}' declares no warehouse",
        "declare a warehouse",
    ),
    spec(
        "SST-VAL528",
        Severity.WARNING,
        "Agent toolset makes the tool surface non-static",
        "agent '{artifact}' declares an agent toolset",
        "accept that tool-name uniqueness and eval coverage are incomplete here",
    ),
    spec(
        "SST-VAL529",
        Severity.ERROR,
        "Built-in tool type emits a tool_resources entry",
        "agent '{artifact}': built-in tool '{name}' would emit tool_resources",
        "remove the resources entry",
    ),
    spec(
        "SST-VAL530",
        Severity.ERROR,
        "tool_resources key matches no rendered tool",
        "agent '{artifact}': tool_resources key '{key}' matches no tools[].name",
        "align the key with the rendered tool name",
    ),
    spec(
        "SST-VAL531",
        Severity.WARNING,
        "Resolved external object does not exist in the target",
        "agent '{artifact}': '{value}' does not exist in target '{target}'",
        "publish it first, or correct the reference",
    ),
    spec(
        "SST-VAL532",
        Severity.WARNING,
        "External object signature disagrees with the input schema",
        "agent '{artifact}': '{value}' signature {found} differs from input_schema {expected}",
        "align the schema with the object",
    ),
    spec(
        "SST-VAL533",
        Severity.INFO,
        "generic tool resource key unverified",
        "agent '{artifact}': resource key '{key}' for a generic tool is unverified",
        "confirm against DESCRIBE AGENT on a live agent",
    ),
    spec(
        "SST-VAL534",
        Severity.WARNING,
        "query_timeout exceeds the warehouse statement timeout",
        "agent '{artifact}': query_timeout {found} exceeds STATEMENT_TIMEOUT_IN_SECONDS {expected}, "
        "which silently wins",
        "lower query_timeout, or raise the warehouse setting",
    ),
    spec(
        "SST-VAL535",
        Severity.WARNING,
        "Instructions name a tool that does not exist",
        "agent '{artifact}': instructions name tool '{name}', absent from tools:",
        "correct the instruction, or add the tool",
    ),
    spec(
        "SST-VAL536",
        Severity.WARNING,
        "Instructions contradict a tool description",
        "agent '{artifact}': instructions route {value} to '{name}', documented as excluding it",
        "reconcile the instruction and the description",
    ),
    spec(
        "SST-VAL537",
        Severity.WARNING,
        "Sample question is a relative-dated duplicate of an eval question",
        "agent '{artifact}': sample question '{value}' is relative-dated and matches an eval row",
        "pin the date, and keep the two sets distinct",
    ),
    spec(
        "SST-VAL538",
        Severity.ERROR,
        "Skill source does not pin an immutable version",
        "agent '{artifact}': skill source '{name}' does not pin an immutable version",
        "pin a committed version; `LIVE` and an omitted version are both refused HERE -- Snowflake refuses neither",
    ),
    spec(
        "SST-VAL539",
        Severity.ERROR,
        "Skill source points at a mutable stage path",
        "agent '{artifact}': skill source '{name}' is a STAGE path into a mutable bundle",
        "reference a CORTEX EXTENSION version instead",
    ),
    spec(
        "SST-VAL540",
        Severity.ERROR,
        "SKILL-type extension source has no name",
        "agent '{artifact}': the skill source for skill('{path}') omits name",
        "declare name; it is optional only for PLUGIN-type",
    ),
    spec(
        "SST-VAL541",
        Severity.WARNING,
        "Two skill entries contribute the same member name",
        "agent '{artifact}': '{a}' and '{b}' both contribute '{name}'; the later wins",
        "rename one of them",
    ),
    spec(
        "SST-VAL542",
        Severity.WARNING,
        "Consuming role lacks READ on an extension",
        "agent '{artifact}': {value} lacks READ on extension '{name}'",
        "grant READ before publishing",
    ),
    spec(
        "SST-VAL543",
        Severity.ERROR,
        "Orchestration model is not in the allowlist",
        "agent '{artifact}': models.orchestration '{found}' is not in the allowlist",
        "add it to the config allowlist, or use an allowed model",
    ),
    spec(
        "SST-VAL544",
        Severity.ERROR,
        "Orchestration model is auto while a blocking eval exists",
        "agent '{artifact}': models.orchestration is auto and a blocking eval is configured",
        "pin the model explicitly",
    ),
    spec(
        "SST-VAL545",
        Severity.ERROR,
        "tool_not_accessible is misplaced or invalid",
        "agent '{artifact}': tool_not_accessible {detail}",
        "set it to accept, reject or legacy on the top-level orchestration key",
    ),
    spec(
        "SST-VAL546",
        Severity.ERROR,
        "analytical_search enabled with no Cortex Search tool",
        "agent '{artifact}': analytical_search is true and no cortex_search tool is declared",
        "declare a cortex_search tool, or disable analytical_search",
    ),
    spec(
        "SST-VAL547",
        Severity.WARNING,
        "Token budget read as a cost ceiling",
        "agent '{artifact}': budget.tokens covers orchestration only",
        "treat it as an orchestration bound, not a spend cap",
    ),
    spec(
        "SST-VAL548",
        Severity.WARNING,
        "Profile value outside its declared allowlist or form",
        "agent '{artifact}': {field} '{found}' {detail}",
        "use an allowlisted avatar, or a plain colour name or var(--token)",
    ),
    spec(
        "SST-VAL549",
        Severity.WARNING,
        "display_name collides with another agent",
        "agent '{artifact}': display_name '{value}' is shared with {other}",
        "rename one of them; it is the conversational handle",
    ),
    spec(
        "SST-VAL550",
        Severity.ERROR,
        "Deprecated or dropped version is still referenced",
        "agent '{artifact}': {detail}",
        "clear the alias, or retain the version",
    ),
)
