"""Validation codes 8xx (VAL): skills, plugins, and CoCo Desktop profiles.

Skill and plugin bundles, their publication channels and stages, and CoCo Desktop
profiles with the hooks, MCP configs, and commands they name.
"""

from __future__ import annotations

from snowflake_semantic_tools.domain.diagnostics.core import ErrorSpec, Severity, spec

TITLE: str = "Validation"

SPECS: tuple[ErrorSpec, ...] = (
    spec(
        "SST-VAL801",
        Severity.ERROR,
        "Skill folder layout is wrong",
        "'{artifact}': {detail}",
        "put SKILL.md at the folder root, with scripts beside it",
    ),
    spec(
        "SST-VAL802",
        Severity.ERROR,
        "Skill is not published as a typed CORTEX EXTENSION",
        "skill '{artifact}': TYPE is {found}",
        "publish with an explicit TYPE of SKILL or PLUGIN",
    ),
    spec(
        "SST-VAL803",
        Severity.ERROR,
        "Extension version is not immutable and SHA-derived",
        "skill '{artifact}': version '{value}' is not SHA-derived",
        "derive the version from the content hash, using +version_prefix",
    ),
    spec(
        "SST-VAL804",
        Severity.WARNING,
        "Extension version referenced by no agent",
        "{artifact}: version {value} is referenced by no agent",
        "reference it, or stop publishing it",
    ),
    spec(
        "SST-VAL805",
        Severity.WARNING,
        "Repo and catalog disagree",
        "skill reconciliation: {value}",
        "publish the missing sources, and reap the orphan objects",
    ),
    spec(
        "SST-VAL806",
        Severity.WARNING,
        "Folder-to-schema split introduced",
        "skill '{artifact}' would land in schema '{value}'",
        "split for confidentiality, not tidiness; the agent owner then needs USAGE per schema",
    ),
    spec(
        "SST-VAL807",
        Severity.ERROR,
        "Certification attempted by moving schemas",
        "skill '{artifact}': certification would change its schema",
        "certify with the SNOWFLAKE.CORE.CERTIFICATION_STATUS tag",
    ),
    spec(
        "SST-VAL808",
        Severity.ERROR,
        "Referenced bundle path does not resolve",
        "skill '{artifact}': '{path}' is referenced and absent from the bundle",
        "add the file, or correct the reference",
    ),
    spec(
        "SST-VAL809",
        Severity.ERROR,
        "Flattened file names collide",
        "skill '{artifact}': '{a}' and '{b}' flatten to one name",
        "rename one of the authored files",
    ),
    spec(
        "SST-VAL810",
        Severity.ERROR,
        "Flattening did not rewrite a subdirectory reference",
        "skill '{artifact}': '{path}' does not resolve inside the published bundle",
        "rewrite every subdirectory reference, then re-check the paths",
    ),
    spec(
        "SST-VAL811",
        Severity.WARNING,
        "Flattened bundle exceeds the size budget",
        "'{artifact}': bundle is {size} bytes, over {expected}",
        "move bulk content out of the bundle",
    ),
    spec(
        "SST-VAL812",
        Severity.WARNING,
        "SKILL.md exceeds the size budget",
        "skill '{artifact}': SKILL.md is {size} bytes, over {expected}",
        "move bulk content into a referenced file",
    ),
    spec(
        "SST-VAL813",
        Severity.WARNING,
        "Bundled file is never referenced",
        "skill '{artifact}': '{path}' is never referenced from the skill's Markdown",
        "reference it, or remove it",
    ),
    spec(
        "SST-VAL814",
        Severity.WARNING,
        "Bundle carries a script with no consumer that can run it",
        "skill '{artifact}': '{path}' is executable and no consuming agent enables code_execution",
        "enable code_execution, or drop the script",
    ),
    spec(
        "SST-VAL815",
        Severity.WARNING,
        "Bundled script reads a credential or an absolute local path",
        "skill '{artifact}': '{path}' contains {detail}",
        "parameterise it; a path that resolves locally will not resolve in the sandbox",
    ),
    spec(
        "SST-VAL816",
        Severity.INFO,
        "SKILL.md and bundle byte split",
        "skill '{artifact}': {value}",
        None,
    ),
    spec(
        "SST-VAL817",
        Severity.ERROR,
        "No publication channel configured",
        "{key}: configures neither the catalog nor the stage channel",
        "configure at least one channel",
    ),
    spec(
        "SST-VAL818",
        Severity.ERROR,
        "Flatten settings are wrong for a channel",
        "config key '{key}' is {found}; it must be {expected}",
        "set catalog flatten true and stage flatten false",
    ),
    spec(
        "SST-VAL819",
        Severity.ERROR,
        "Stage auto_compress is enabled",
        "config key '{key}' is {found}; it must be {expected}",
        "set it false",
    ),
    spec(
        "SST-VAL820",
        Severity.ERROR,
        "Stage PUT target does not end in a separator",
        "skill '{artifact}': PUT target '{path}' does not end in '/'",
        "append a trailing slash",
    ),
    spec(
        "SST-VAL821",
        Severity.ERROR,
        "Stage layout is not by_type",
        "config key '{key}' value {found} is outside {expected}",
        "set layout to by_type",
    ),
    spec(
        "SST-VAL822",
        Severity.ERROR,
        "Uploaded artifact has no registry pointer",
        "skill '{artifact}': '{path}' was uploaded with no PROFILE_REGISTRY pointer",
        "write the pointer as part of the same publish",
    ),
    spec(
        "SST-VAL823",
        Severity.ERROR,
        "Profile content hash does not cover every shipped tree",
        "skill '{artifact}': hash omits {value}",
        "include every shipped tree in the hash",
    ),
    spec(
        "SST-VAL824",
        Severity.ERROR,
        "Deleted file survives into the next version",
        "skill '{artifact}': '{path}' was deleted and is still published",
        "build each version from empty, or issue explicit removals",
    ),
    spec(
        "SST-VAL825",
        Severity.ERROR,
        "Version name is not collision-free under parallel deploys",
        "skill '{artifact}': version name '{value}' is not collision-free",
        "derive the version from the content SHA",
    ),
    spec(
        "SST-VAL826",
        Severity.ERROR,
        "Grants issued before certification succeeded",
        "skill '{artifact}': grants would be issued before certification",
        "grant only after certification succeeds, and name the role TYPE explicitly",
    ),
    spec(
        "SST-VAL827",
        Severity.ERROR,
        "Identifier interpolated into DDL without validation",
        "skill '{artifact}': '{value}' reaches DDL unvalidated",
        "validate every interpolated identifier at parse time",
    ),
    spec(
        "SST-VAL828",
        Severity.ERROR,
        "Partial deploy reported as aggregate success",
        "skill '{artifact}': {detail}",
        "report per-channel status separately",
    ),
    spec(
        "SST-VAL829",
        Severity.WARNING,
        "Channel content hashes diverge beyond flattening",
        "skill '{artifact}': catalog and stage hashes diverge by {value}",
        "compare the two bundles",
    ),
    spec(
        "SST-VAL830",
        Severity.WARNING,
        "Skill reaches neither channel",
        "skill '{artifact}' is published nowhere",
        "reference it from a profile, or enable a channel",
    ),
    spec(
        "SST-VAL831",
        Severity.INFO,
        "CORTEX EXTENSION DDL surface used",
        "skill '{artifact}': {value}",
        None,
    ),
    spec(
        "SST-VAL832",
        Severity.ERROR,
        "Skill name is not globally unique across extensions",
        "'{artifact}' collides with '{other}' as one extension name",
        "rename one of them",
    ),
    spec(
        "SST-VAL833",
        Severity.WARNING,
        "Script names a path that flattening renames",
        "skill '{artifact}': '{path}' names '{target}', which the catalog bundle renames",
        "keep files a script reads beside SKILL.md, or pass the path in as an argument",
    ),
    spec(
        "SST-VAL834",
        Severity.ERROR,
        "Bundle exceeds the extension scan limits",
        "'{artifact}': {detail}",
        "split the bundle; Snowflake scans at most 50 files, 2 MiB per file, 10 MiB per version",
    ),
    spec(
        "SST-VAL835",
        Severity.ERROR,
        "Plugin member is not a project skill",
        "plugin '{artifact}': member '{name}' is not a skill in this project",
        "add the skill under the skills directory, or remove it from the plugin",
    ),
    spec(
        "SST-VAL836",
        Severity.ERROR,
        "Plugin member cannot be bundled",
        "plugin '{artifact}': member '{name}' has errors, so the plugin cannot be bundled",
        "fix the member skill's errors",
    ),
    spec(
        "SST-VAL837",
        Severity.WARNING,
        "Plugin lists a member twice",
        "plugin '{artifact}': lists '{name}' more than once",
        "list each member once",
    ),
    spec(
        "SST-VAL838",
        Severity.ERROR,
        "Version set on a project-published extension",
        "agent '{artifact}': skill source '{name}' sets version, which SST manages for {kind}('{path}')",
        "delete version; SST pins the published content-hash alias",
    ),
    spec(
        "SST-VAL839",
        Severity.ERROR,
        "Skill version pinned to the commit SHA",
        "agent '{artifact}': skill source '{name}' pins var('sha_version'), which names no published version",
        "use skill() or plugin() with no version, or pin a real version of a consumed extension",
    ),
    spec(
        "SST-VAL840",
        Severity.ERROR,
        "Skill source name does not match its extension",
        "agent '{artifact}': skill source name '{name}' must be {expected}",
        "use the skill's name, or a member name of the plugin",
    ),
    spec(
        "SST-VAL841",
        Severity.WARNING,
        "Catalog serves a different version",
        "{artifact}: the catalog will serve {found} of {target}, not {value}, because {detail}",
        "agents pin their version and are unaffected; to serve this version in the catalog, "
        "set `+certified: true` and un-certify any later certified version in Snowsight",
    ),
    spec(
        "SST-VAL843",
        Severity.WARNING,
        "Two artifacts publish to one Snowflake name",
        "{a} and {b} both publish to {target}",
        "rename one of them; plans and reports that name the object become ambiguous",
    ),
    spec(
        "SST-VAL844",
        Severity.ERROR,
        "Profile names a skill the project does not have",
        "profile '{artifact}': skill '{name}' is not a skill in this project",
        "add the skill under the skills directory, or remove it from the profile",
    ),
    spec(
        "SST-VAL845",
        Severity.WARNING,
        "Profile repeats a shared skill or command",
        "profile '{artifact}': {kind} '{name}' already reaches every profile through shared/",
        "remove it from the profile",
    ),
    spec(
        "SST-VAL846",
        Severity.ERROR,
        "Profile names an unknown hook",
        "profile '{artifact}': hook '{name}' is not defined under the hooks directory",
        "add the hook, or remove it from the profile",
    ),
    spec(
        "SST-VAL847",
        Severity.ERROR,
        "Profile names an unknown MCP config",
        "profile '{artifact}': MCP config '{name}' is not defined under the MCP servers directory",
        "add the config, or remove it from the profile",
    ),
    spec(
        "SST-VAL848",
        Severity.ERROR,
        "MCP server entry is not a configuration",
        "profile '{artifact}': MCP server '{name}' is not a configuration object",
        "replace the placeholder with a server definition, or stop referencing the config",
    ),
    spec(
        "SST-VAL849",
        Severity.ERROR,
        "Two MCP configs define one server",
        "profile '{artifact}': MCP server '{name}' is defined by both '{a}' and '{b}'",
        "rename one server, or reference only one of the configs",
    ),
    spec(
        "SST-VAL850",
        Severity.ERROR,
        "MCP config carries a literal credential",
        "MCP config '{artifact}': server '{name}' sets '{key}' to a literal value",
        "use a ${VARIABLE} placeholder; published configs are readable by every profile user",
    ),
    spec(
        "SST-VAL851",
        Severity.ERROR,
        "Profile key is not accepted",
        "profile '{artifact}': '{key}' is not accepted: {reason}",
        "delete the key",
    ),
    spec(
        "SST-VAL852",
        Severity.ERROR,
        "Hook definition is incomplete or ambiguous",
        "hook '{artifact}': {detail}",
        "declare event, command, and exactly one script, naming it with script: when the folder holds several files",
    ),
    spec(
        "SST-VAL853",
        Severity.ERROR,
        "MCP config is not valid",
        "MCP config '{artifact}': {detail}",
        'write mcp.json as {"mcpServers": {"<name>": {...}}}',
    ),
    spec(
        "SST-VAL854",
        Severity.INFO,
        "Profile registry is not the one Desktop reads",
        "profiles publish to {value}; CoCo Desktop reads only {expected}",
        "point skills.stage at the Desktop registry to publish for real, or keep this for rehearsal",
    ),
    spec(
        "SST-VAL855",
        Severity.ERROR,
        "Profile includes a skill or plugin with errors",
        "profile '{artifact}': {kind} '{name}' has errors, so the profile cannot publish",
        "fix the errors reported for it",
    ),
    spec(
        "SST-VAL856",
        Severity.ERROR,
        "Agent references an extension that cannot publish",
        "agent '{artifact}': {kind}('{name}') has no version to pin because {reason}",
        "fix the diagnostic that names the cause; the reference resolves once the extension publishes",
    ),
    spec(
        "SST-VAL857",
        Severity.ERROR,
        "File name cannot be published to a stage",
        "{artifact}: {value} cannot be staged, because '{found}' is not made only of {expected}",
        "rename the file or folder; a stage rejects any other name, so apply would fail partway through",
    ),
    spec(
        "SST-VAL858",
        Severity.ERROR,
        "Profile names an unknown command",
        "profile '{artifact}': command '{name}' is not a .md file under the commands directory",
        "name a command by its path below project.commands_dir without .md, such as sql/check",
    ),
    spec(
        "SST-VAL859",
        Severity.ERROR,
        "Command file is invalid",
        "command '{artifact}': {detail}",
        "frontmatter is optional; when present it is a YAML mapping of description, allowed-tools, skill, and hidden",
    ),
    spec(
        "SST-VAL860",
        Severity.ERROR,
        "Profile names an unknown plugin",
        "profile '{artifact}': plugin '{name}' is not a plugin under the plugins directory",
        "name a plugin folder that has a plugin.yml",
    ),
)
