"""The generated reference pages, rendered from the engine's own registries.

`sst docs` writes these pages and `sst docs --check` fails when a committed copy
differs, so the reference cannot drift from the artifact types, diagnostic codes,
configuration keys, and command-line flags the engine actually has.

Everything here is pure: the command tree arrives as `CommandDoc` records built by
the CLI, so this ring never imports click.
"""

from __future__ import annotations

import re
import string
from collections.abc import Iterable, Mapping
from dataclasses import dataclass

from snowflake_semantic_tools.domain.diagnostics import ERROR_REGISTRY, ErrorSpec, Severity
from snowflake_semantic_tools.domain.diagnostics.specs import SUBSYSTEMS
from snowflake_semantic_tools.domain.model.config_schema import CONFIG_SCHEMA, ConfigKey, KeyKind, KeyStatus
from snowflake_semantic_tools.domain.model.registry import (
    ARTIFACT_REGISTRY,
    ArtifactLifecycle,
    ArtifactType,
    AttachRule,
    GrantPreservation,
    MemberSource,
    Registry,
)

REFERENCE_DIR = "docs/reference"
GENERATED = "<!-- Generated by `sst docs` from the engine's registries. Edit the registries, not this file. -->"

_KIND_LABELS: Mapping[KeyKind, str] = {
    KeyKind.BLOCK: "block",
    KeyKind.MAP: "map",
    KeyKind.STRING: "string",
    KeyKind.BOOLEAN: "boolean",
    KeyKind.INTEGER: "integer",
    KeyKind.LIST: "list",
    KeyKind.ENUM: "enum",
    KeyKind.ANY: "any",
}

_GRANTS: Mapping[GrantPreservation, str] = {
    GrantPreservation.CLAUSE: "kept across a replace by `COPY GRANTS`",
    GrantPreservation.REPLAY: "re-applied after a replace",
    GrantPreservation.NONE: "never touched: the object is not replaced",
}


@dataclass(frozen=True, slots=True)
class OptionDoc:
    """One command-line option, as the reference presents it."""

    flags: str
    value: str | None
    default: str | None
    help: str
    multiple: bool = False
    required: bool = False


@dataclass(frozen=True, slots=True)
class CommandDoc:
    """One command or command group of the `sst` tree."""

    path: str
    description: str
    options: tuple[OptionDoc, ...] = ()
    subcommands: tuple[str, ...] = ()


def reference_pages(
    commands: tuple[CommandDoc, ...],
    global_options: tuple[OptionDoc, ...],
    exit_codes: tuple[tuple[int, str, str], ...],
) -> dict[str, str]:
    """Every generated page, keyed by its path relative to the repository root."""
    return {
        f"{REFERENCE_DIR}/artifacts.md": render_artifacts(),
        f"{REFERENCE_DIR}/cli.md": render_cli(commands, global_options, exit_codes),
        f"{REFERENCE_DIR}/config.md": render_config(),
        f"{REFERENCE_DIR}/error-codes.md": render_error_codes(),
    }


def error_anchor(code: str) -> str:
    """The fragment GitHub derives from the code's heading in `error-codes.md`."""
    return code.casefold()


# --------------------------------------------------------------------------- artifacts


def render_artifacts(registry: Registry = ARTIFACT_REGISTRY) -> str:
    """Render the artifact reference page from the registry.

    A table of the artifact types and a section for each come first, both in DDL-position
    order, then a table of the member types in clause-position order.
    """
    artifacts = sorted(registry.artifacts.values(), key=lambda item: item.ddl_position)
    lines = [
        "# Artifact reference",
        "",
        GENERATED,
        "",
        "SST publishes the artifact types below. `sst plan` orders changes by each",
        "type's position, lowest first, and always places an artifact after the",
        "artifacts it depends on. Types with a reference function can be named from",
        "another artifact with `{{ <function>('<name>') }}`.",
        "",
        "| Type | Position | Authored in | Publishes | Reference function |",
        "|---|---:|---|---|---|",
    ]
    for artifact in artifacts:
        function = f"`{artifact.ref_function}()`" if artifact.ref_function else "none"
        lines.append(
            f"| [`{artifact.name}`](#{artifact.name}) | {artifact.ddl_position} | "
            f"{_cell(artifact.authored_in)} | {_cell(artifact.publishes)} | {function} |"
        )
    for artifact in artifacts:
        lines.extend(("", f"## {artifact.name}", "", _prose(artifact.summary), ""))
        lines.extend(_artifact_facts(artifact))
    members = sorted(registry.members.values(), key=lambda item: item.clause_position)
    lines.extend(
        (
            "",
            "## Semantic view members",
            "",
            "Members are authored separately and attach to semantic views; they are not",
            "published on their own. Members read from dbt model metadata come from the",
            "`config.meta.sst` block of each model's columns.",
            "",
            "| Member | Owner | Authored as | Attaches by | Reference function |",
            "|---|---|---|---|---|",
        )
    )
    for member in members:
        source = f"`{member.root_key}:` files" if member.source is MemberSource.FILES else "dbt column metadata"
        attaches = "table membership" if member.attaches_by is AttachRule.TABLE_MEMBERSHIP else "view name"
        function = f"`{member.ref_function}()`" if member.ref_function else "none"
        lines.append(f"| `{member.name}` | `{member.owner_type}` | {source} | {attaches} | {function} |")
    return "\n".join(lines) + "\n"


def _artifact_facts(artifact: ArtifactType) -> list[str]:
    """List an artifact type's facts as the Markdown bullets of its section.

    Position, lifecycle, update behavior, grants, and `--prune` always appear; dependencies,
    version pins, and member types appear only when the type has them.
    """
    composite = artifact.lifecycle is ArtifactLifecycle.COMPOSITE
    facts = [
        f"- Position: {artifact.ddl_position}",
        "- Lifecycle: "
        + ("composite -- several objects, reconciled together" if composite else "one Snowflake object"),
        "- On update: " + ("replaced" if artifact.replaces_on_update else "altered or re-versioned in place"),
        f"- Grants: {_GRANTS[artifact.grant_preservation]}",
        "- `--prune`: " + ("drops it once its source is deleted" if artifact.prunable else "never drops it"),
    ]
    if artifact.dependency_types:
        facts.append("- Applied after: " + ", ".join(f"`{name}`" for name in artifact.dependency_types))
    if artifact.pins_versions_of:
        facts.append(
            "- Pins the published version of: "
            + ", ".join(f"`{name}`" for name in artifact.pins_versions_of)
            + " -- so a change to it plans only together with them"
        )
    if artifact.member_types:
        facts.append("- Members: " + ", ".join(f"`{name}`" for name in artifact.member_types))
    return facts


# ------------------------------------------------------------------------- error codes


def render_error_codes(registry: Mapping[str, ErrorSpec] = ERROR_REGISTRY) -> str:
    """Render the error code reference page: every code under its subsystem, with its message and any fix.

    Subsystems appear in `SUBSYSTEMS` order, each with its codes sorted; a subsystem with no
    codes is left out.

    Raises:
        ValueError: a code belongs to a subsystem `SUBSYSTEMS` does not list, so the page would
            have no section for it.
    """
    by_subsystem: dict[str, list[ErrorSpec]] = {}
    for spec in registry.values():
        by_subsystem.setdefault(spec.subsystem, []).append(spec)
    unknown = sorted(set(by_subsystem) - set(SUBSYSTEMS))
    if unknown:
        raise ValueError(f"diagnostic subsystems without a reference section: {', '.join(unknown)}")
    lines = [
        "# Error code reference",
        "",
        GENERATED,
        "",
        "Every diagnostic SST reports carries a stable code, and the `docs:` link printed",
        "under a diagnostic points at its entry here. Codes are never reused.",
        "",
        "- **error** blocks the command.",
        "- **warning** does not block, and becomes an error under `--strict` or",
        "  `validation.strict: true`.",
        "- **info** never blocks.",
        "",
        "Placeholders in a message are shown as `<name>`. Codes marked *always an error*",
        "cannot be downgraded by any setting.",
        "",
        "## Contents",
        "",
    ]
    ordered = [prefix for prefix in SUBSYSTEMS if prefix in by_subsystem]
    for prefix in ordered:
        title = f"{SUBSYSTEMS[prefix]} ({prefix})"
        lines.append(f"- [{title}](#{_slug(title)}) -- {len(by_subsystem[prefix])} codes")
    for prefix in ordered:
        lines.extend(("", f"## {SUBSYSTEMS[prefix]} ({prefix})"))
        for spec in sorted(by_subsystem[prefix], key=lambda item: item.code):
            lines.extend(_error_entry(spec))
    return "\n".join(lines) + "\n"


def _error_entry(spec: ErrorSpec) -> list[str]:
    severity = spec.severity.name.lower()
    qualifier = ", always an error" if spec.severity is Severity.ERROR and not spec.demotable else ""
    entry = [
        "",
        f"### {spec.code}",
        "",
        f"**{_prose(spec.title)}** ({severity}{qualifier})",
        "",
        _code(_template(spec)),
    ]
    if spec.suggestion:
        entry.extend(("", f"Fix: {_prose(spec.suggestion)}"))
    return entry


def _template(spec: ErrorSpec) -> str:
    """The message with each placeholder shown as `<name>` and literal braces restored."""
    parts: list[str] = []
    for literal, field, _format, _conversion in string.Formatter().parse(spec.template):
        parts.append(literal)
        if field is not None:
            parts.append(f"<{field}>")
    return "".join(parts)


# ------------------------------------------------------------------------------ config


def _deprecated_rows(schema: tuple[ConfigKey, ...]) -> list[str]:
    """Return the deprecated-keys section: each key and the key it is read as."""
    lines = [
        "",
        "## Deprecated keys",
        "",
        "Each is read as the key that replaced it, with a warning (`SST-CFG200`) naming it.",
        "",
        "| Key | Read as |",
        "|---|---|",
    ]
    lines.extend(
        f"| `{_cell(key.path)}` | `{_cell(key.replacement or '')}` |"
        for key in schema
        if key.status is KeyStatus.DEPRECATED
    )
    return lines


def render_config(schema: tuple[ConfigKey, ...] = CONFIG_SCHEMA) -> str:
    """Render the configuration reference page from the configuration schema.

    Current keys are grouped by top-level block, in schema order, and a block's own key gives
    its summary and notes. A table of unsupported keys follows when there are any, then one of
    removed keys, where a key that names no code links SST-CFG043. A default that starts with
    "the " is prose and shown as written; any other default is shown as code.
    """
    current = [key for key in schema if key.status is KeyStatus.CURRENT]
    unsupported = [key for key in schema if key.status is KeyStatus.UNSUPPORTED]
    removed = [key for key in schema if key.status is KeyStatus.REMOVED]
    lines = [
        "# Configuration reference",
        "",
        GENERATED,
        "",
        "`sst_config.yml` sits at the project root. Every key SST reads is listed here,",
        "and nothing else is read:",
        "",
        "- an unknown key is a warning (`SST-CFG003`), or an error when it is a",
        "  misspelled top-level block (`SST-CFG007`);",
        "- an unsupported key is reserved for a later release and is an error until SST",
        "  reads it (`SST-CFG044`);",
        "- a removed key is an error that says what replaced it.",
        "",
        "Keys that start with `+` set a default that nested folder routes and",
        "individual artifacts inherit. In a key path, `<route>` stands for a folder",
        "name and `<name>` for any entry of a name map.",
    ]
    blocks: dict[str, list[ConfigKey]] = {}
    for key in current:
        blocks.setdefault(key.segments[0], []).append(key)
    for block, keys in blocks.items():
        head = next((key for key in keys if key.path == block), None)
        lines.extend(("", f"## {block}"))
        if head is not None:
            lines.extend(("", _prose(head.summary)))
            notes = _notes(head)
            if notes:
                lines.extend(("", " ".join(notes)))
        rows = [key for key in keys if key.path != block]
        if not rows:
            continue
        lines.extend(("", "| Key | Type | Default | Description |", "|---|---|---|---|"))
        for key in rows:
            default = f"`{key.default}`" if key.default and not key.default.startswith("the ") else (key.default or "")
            lines.append(f"| `{_cell(key.path)}` | {_type(key)} | {_cell(default)} | {_cell(_description(key))} |")
    if unsupported:
        lines.extend(
            (
                "",
                "## Unsupported keys",
                "",
                "These keys are reserved for a later release. Setting one is an error until SST",
                "reads it, so a setting cannot look as though it takes effect when it does not.",
                "",
                "| Key | Type | Description |",
                "|---|---|---|",
            )
        )
    for key in unsupported:
        lines.append(f"| `{_cell(key.path)}` | {_type(key)} | {_cell(_description(key))} |")
    lines.extend(_deprecated_rows(schema))
    lines.extend(
        (
            "",
            "## Removed keys",
            "",
            "These keys were read by SST 0.3 or an earlier 1.0 draft. Each is an error",
            "now, so a setting that no longer does anything cannot pass review looking",
            "as though it still does.",
            "",
            "| Key | Why it was removed | Code |",
            "|---|---|---|",
        )
    )
    for key in removed:
        code = key.code or "SST-CFG043"
        link = f"[`{code}`](error-codes.md#{error_anchor(code)})"
        lines.append(f"| `{_cell(key.path)}` | {_cell(_prose(key.summary))} | {link} |")
    return "\n".join(lines) + "\n"


def _notes(key: ConfigKey) -> list[str]:
    notes = []
    if key.one_of:
        notes.append("Declare at least one of " + ", ".join(f"`{name}`" for name in key.one_of) + ".")
    return notes


def _type(key: ConfigKey) -> str:
    label = _KIND_LABELS[key.kind]
    if key.choices:
        label += ": " + ", ".join(f"`{choice}`" for choice in key.choices)
    if key.minimum is not None and key.maximum is not None:
        label += f", {key.minimum} to {key.maximum}"
    if key.required:
        label += ", required"
    return label


def _description(key: ConfigKey) -> str:
    return " ".join((_prose(key.summary), *_notes(key)))


# --------------------------------------------------------------------------------- cli


def render_cli(
    commands: tuple[CommandDoc, ...],
    global_options: tuple[OptionDoc, ...],
    exit_codes: tuple[tuple[int, str, str], ...],
) -> str:
    """Render the CLI reference page from the command tree the CLI describes.

    A table of each command's first paragraph, the global options, and the exit codes come
    first, then a section per command: a group lists its subcommands, and any other command
    shows its usage and options.

    Args:
        commands: Every command and group, in the order the page lists them.
        global_options: The options that go before the command name.
        exit_codes: `(code, name, meaning)` for each exit code, in the order the page lists them.
    """
    lines = [
        "# CLI reference",
        "",
        GENERATED,
        "",
        "Run `sst <command> --help` for the same text in a terminal. Every command",
        "that reports results accepts `--output json`, which prints exactly one",
        "versioned JSON envelope on stdout and nothing else.",
        "",
        "## Commands",
        "",
        "| Command | Summary |",
        "|---|---|",
    ]
    for command in commands:
        summary = command.description.split("\n\n", 1)[0].replace("\n", " ")
        lines.append(f"| [`{command.path}`](#{_slug(command.path)}) | {_cell(_prose(summary))} |")
    lines.extend(("", "## Global options", "", "These go before the command name.", ""))
    lines.extend(_option_table(global_options))
    lines.extend(("", "## Exit codes", "", "| Code | Name | Meaning |", "|---:|---|---|"))
    lines.extend(f"| {code} | `{name}` | {_cell(_prose(meaning))} |" for code, name, meaning in exit_codes)
    for command in commands:
        lines.extend(("", f"## {command.path}", "", _prose(command.description), ""))
        if command.subcommands:
            lines.append(
                "Subcommands: " + ", ".join(f"[`{name}`](#{_slug(name)})" for name in command.subcommands) + "."
            )
            continue
        lines.extend(("```text", f"{command.path} [OPTIONS]", "```", ""))
        lines.extend(_option_table(command.options))
    return "\n".join(lines).rstrip("\n") + "\n"


def _option_table(options: Iterable[OptionDoc]) -> list[str]:
    rows = ["| Option | Value | Default | Description |", "|---|---|---|---|"]
    for option in options:
        value = option.value or "flag"
        if option.multiple:
            value += ", repeatable"
        if option.required:
            value += ", required"
        default = f"`{option.default}`" if option.default else ""
        rows.append(f"| `{_cell(option.flags)}` | {_cell(value)} | {_cell(default)} | {_cell(_prose(option.help))} |")
    return rows


# ----------------------------------------------------------------------------- helpers


_CODE_SPAN = re.compile(r"(`+)(?:(?!\1).)+?\1")


def _prose(text: str) -> str:
    """Markdown-safe text: an angle bracket outside a code span would read as an HTML tag.

    Inside a code span an entity renders literally, so spans are left exactly as written.
    """
    parts: list[str] = []
    position = 0
    for span in _CODE_SPAN.finditer(text):
        parts.append(text[position : span.start()].replace("<", "&lt;").replace(">", "&gt;"))
        parts.append(span.group(0))
        position = span.end()
    parts.append(text[position:].replace("<", "&lt;").replace(">", "&gt;"))
    return "".join(parts)


def _cell(text: str) -> str:
    return text.replace("|", "\\|").replace("\n", " ")


def _code(text: str) -> str:
    """Inline code that survives backticks inside the text."""
    longest = max((len(run) for run in re.findall(r"`+", text)), default=0)
    fence = "`" * (longest + 1)
    padding = " " if text.startswith("`") or text.endswith("`") else ""
    return f"{fence}{padding}{text}{padding}{fence}"


def _slug(title: str) -> str:
    """GitHub's heading anchor: lowercase, punctuation dropped, spaces to hyphens."""
    return re.sub(r"[^a-z0-9 _-]", "", title.casefold()).replace(" ", "-")
